---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: cloudflared-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    credentials:
      existingSecret: cloudflared-credentials
    config:
      tunnel: homelab
      ingress:
        - hostname: '*.${SECRET_PUBLIC_DOMAIN}'
          service: https://ingress-nginx-controller.ingress-nginx
          originRequest:
            noTLSVerify: true
        - service: http_status:404
