# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflared-credentials
    namespace: cloudflare
data:
    credentials.json: ENC[AES256_GCM,data:UcqaN0wy49ZgzUO1smimwlVwbAkkM2E/TII4hTSrqFEFTQZWfveHgDTD0o8shPODLx3diGeZkM65Yfc7hLDAOxANMoMj0UWt+O+PXOX1fatKcJ96/8ypXV5kbHI6wuHiplODfDiHsNF7VN+AF89a15Ftd4Q/xYaT/DouuvE7Kf/0nN/inm/yE2c/Cn5K1s7mVFoyz+ug9Ika14Bx2HVTxtq5Ui9FT0U2Kgqg4L9Km3h1QnhB1kChEosn92mpSQ2Y8WwRbMQt9UyeRK52ajD+5Z74jfmyabL/APhGp0PinByZNg7k2+SHVgEpJB/wnydQs65WbdQzVIqgiZlRyL8uxoOkzuMYLXfERj3UiyHx3ZkeW98DVh2qxqZqSqZJma0rw4/gaHpLEKd8RcWc7ABBuQ==,iv:fXhcxVc/kkkXsTePESZnKtpftZYUnUL9evjHcTb3Hvw=,tag:vctIbDoEA6xzsL7oPZEypg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-03T16:05:17Z"
    mac: ENC[AES256_GCM,data:Oe/4/p/WmM98BTPV3UVlQ2FdNYDCrhpgjPxHBE4m4n3FpIBlOXakpMSrbckIalFuwIY0AShdewy5S7bnIQa/QWtu1hyCF0M8cLEBXPfvVl0KSCrjT5ql3PGfbFLMeEQkCyPo44eJQ8jIE7yslUvBb8o6y0/LSZe5x333/Eg8uEk=,iv:K+JjsV/aK6FIDdwLMv4BKfEGLMJ4KdGEMTwJkddZzl4=,tag:vhxQ/ZzNoh4stZPiMKdXVA==,type:str]
    pgp:
        - created_at: "2022-03-03T16:05:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7ARAAnaLytvA7aYk2XbfJ960nekpgLl7Tb1mEMXLT2NEDK4Ou
            Pgzdebj9NKpqu9ACwZ4crEBVdLKDH8TR+9+Xt55KT77pRjEeQVNwpgco8KUWrUTb
            CBUjG7qPWa+VvMWM+MMK8spGsu4DvNfGTQ2DcecDi2hwmhIIvUNmXEBt33nqXws+
            TNeDk30pj+YQNC53TJN4AwUQjQ9On6vZUCwXWs22RIGeqU6ymhdKNcG3IohoV13+
            Ju8tpXIfkkEy73IiTPWIuVrTK0fGnZEmzCA+EmePfSEY0uEMSNBE+yLNHHZ1JUcK
            9JF98kq8T+6S7de2quKp3IJsdNqZ2FmzSuQL9dFY4mPFtQaSqaoUJJIeh1sowvHJ
            fUZS4TWBqtbjtFR2l1DIJ6gGchwPxHGcHbra8kntyr/i0uaMtrNGRPZlr2SckUKp
            eqMFElptHZMKGE+6t+7ByUGuYibWdHGDFuJMiNPSvBvfIUEwbCFUL1y5UxnAoz3Y
            55g5h2LwtfZ2kjXOk/iFrVZ/5mue3kdXnWLn6/K9x7W1iy5VuJHgtUSlk09KmgzX
            HndEUzaDD48r/iolc9dtjb88Kl1tz7cdi3Q3nSAau6o8xHdAE+aWt8kUrt5AbOSm
            Vp8FeY07V4aIIQTQrjRq+kOPjLm/pHleCeFduPKsgwrin4bL7Z/j4zBIUATj/S3U
            aAEJAhDzHiG4g5RW5JkeCCLZHBTRIuGdy6Tnq7JTKRvVxEMM4ZWCVUrLYMfc8lQl
            6hp6bSK44TG9KQCFFeGNzN2G6gecZCme78nm9bNEdKlGG7cK2jUhjcm0Mx/vZqoI
            6jRXz8vZhN5i
            =Vlvj
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
