---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr-nightly
      tag: v1.0.0.2512
    env:
      TZ: "Europe/Berlin"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/lidarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: lidarr.internal.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: lidarr-server-tls
            hosts:
              - lidarr.internal.${SECRET_PUBLIC_DOMAIN}
    podSecurityContext:
      supplementalGroups:
        - 100
    metrics:
      enabled: false
    persistence:
      config:
        enabled: true
        storageClass: nfs-sc
        size: 1Gi
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
