---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1h
  chart:
    spec:
      chart: keycloak
      version: 18.1.0
      sourceRef:
        kind: HelmRepository
        name: codecentric-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    extraEnv: |
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_PASSWORD
        value: ${SECRET_KEYCLOAK_ADMIN_PASSWORD}
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: id.internal.${SECRET_PUBLIC_DOMAIN}
      servicePort: http
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      rules:
        - host: id.internal.${SECRET_PUBLIC_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - id.internal.${SECRET_PUBLIC_DOMAIN}
          secretName: keycloak-tls-secret
    postgresql:
      enabled: true
      persistence:
        storageClass: nfs-sc
      postgresqlUsername: keycloak
      postgresqlPassword: ${SECRET_KEYCLOAK_DATABASE_PASSWORD}
      postgresqlDatabase: keycloak
