---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    serviceMonitor:
      enabled: true
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      hosts:
        - loki.${SECRET_PRIVATE_DOMAIN}
      tls:
        - secretName: loki-tls-secret
          hosts:
            - loki.${SECRET_PRIVATE_DOMAIN}
