---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2022.3.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  values:
    authentik:
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        password: ${SECRET_AUTHENTIK_DATABASE_PASSWORD}
      email:
        host: mail.${SECRET_PUBLIC_DOMAIN}
        port: 587
        username: ${SECRET_SMTP_USERNAME}
        password: ${SECRET_SMTP_PASSWORD}
        use_tls: true
        from: admin@${SECRET_PUBLIC_DOMAIN}
    postgresql:
      enabled: true
      postgresqlUsername: authentik
      postgresqlPassword: ${SECRET_AUTHENTIK_DATABASE_PASSWORD}
      postgresqlDatabase: authentik
      persistence:
        enabled: true
        storageClass: nfs-sc
        accessModes:
          - ReadWriteOnce
    redis:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: auth.internal.domrocco.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: authentik-tls-secret
          hosts:
            - auth.internal.domrocco.de
