---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    replicaCount: 3
    nfs:
      server: 192.168.180.21
      path: /volume1/kubernetes_nfs
    storageClass:
      name: nfs-sc
      archiveOnDelete: false

