---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 9.5.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/jellyfin
      tag: v10.8.4
    env:
      TZ: "Europe/Berlin"
      JELLYFIN_CACHE_DIR: /config/cache
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "jellyfin.internal.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: nfs-sc
        size: 20Gi
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.180.21"
            path: /volume1/Plex
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
    resources:
      requests:
        memory: 1000Mi
      limits:
        memory: 4000Mi
