---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 2.14.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Real-IP, X-Frame-Options, X-Content-Type-Options, X-Forwarded-Proto"
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.${SECRET_PUBLIC_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      tls:
        - secretName: nextcloud-server-tls
          hosts:
            - cloud.${SECRET_PUBLIC_DOMAIN}
    nextcloud:
      host: cloud.${SECRET_PUBLIC_DOMAIN}
      username: administrator
      password: ${SECRET_NEXTCLOUD_ADMIN_PASSWORD}
      mail:
        enabled: true
        fromAddress: admin
        domain: ${SECRET_PUBLIC_DOMAIN}
        smtp:
          host: mail.${SECRET_PUBLIC_DOMAIN}
          secure: tls
          port: 587
          name: ${SECRET_SMTP_USERNAME}
          password: ${SECRET_SMTP_PASSWORD}
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: true
        redis.config.php: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://cloud.${SECRET_PUBLIC_DOMAIN}',
            'filelocking.enabled' => 'true',
            'loglevel' => '3',
            'enable_previews' => true,
            'enable_previews' => false,
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_provider_url' => 'https://id.internal.${SECRET_PUBLIC_DOMAIN}/auth/realms/chaoscorporation',
            'oidc_login_client_id' => 'nextcloud',
            'oidc_login_client_secret' => '${SECRET_NEXTCLOUD_KEYCLOAK_CLIENT_SECRET}',
            'oidc_login_auto_redirect' => false,
            'oidc_login_logout_url' => 'https://id.internal.${SECRET_PUBLIC_DOMAIN}/auth/realms/chaoscorporation/protocol/openid-connect/logout?redirect_uri=https://cloud.${SECRET_PUBLIC_DOMAIN}',
            'oidc_login_end_session_redirect' => false,
            'oidc_login_default_quota' => '1000000000',
            'oidc_login_button_text' => 'Mit SSO anmelden',
            'oidc_login_hide_password_form' => false,
            'oidc_login_use_id_token' => false,
            'oidc_login_attributes' => array(
              'id' => 'preferred_username',
              'mail' => 'email',
              'groups' => 'ownCloudGroups',
              'is_admin' => 'nextcloud_admin',
            ),
            'oidc_login_default_group' => 'oidc',
            'oidc_login_use_external_storage' => false,
            'oidc_login_scope' => 'openid profile',
            'oidc_login_proxy_ldap' => false,
            'oidc_login_disable_registration' => false,
            'oidc_login_redir_fallback' => false,
            'oidc_login_alt_login_page' => 'assets/login.php',
            'oidc_login_tls_verify' => true,
            'oidc_create_groups' => true,
            'oidc_login_webdav_enabled' => false,
            'oidc_login_public_key_caching_time' => 300,
            'oidc_login_min_time_between_jwks_requests' => 10,
            'oidc_login_well_known_caching_time' => 300,

          );
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
    persistence:
      enabled: true
      storageClass: synology-csi-retain
      accessMode: ReadWriteOnce
      size: 150Gi
    redis:
      enabled: false
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.nextcloud.svc.cluster.local:5432
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_DATABASE_PASSWORD}
      database: nextcloud
    postgresql:
      enabled: true
      auth:
        username: nextcloud
        password: ${SECRET_NEXTCLOUD_DATABASE_PASSWORD}
        database: nextcloud
      primary:
        persistence:
          enabled: true
          storageClass: synology-csi-retain
    cronjob:
      enabled: true
