---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: dcardellino-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.domrocco.de"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      tls:
        - secretName: nextcloud-server-tls
          hosts:
            - cloud.domrocco.de
    nextcloud:
      host: cloud.domrocco.de
      username: administrator
      password: ${SECRET_NEXTCLOUD_ADMIN_PASSWORD}
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: domrocco.de
        smtp:
          host: mail.domrocco.de
          secure: starttls
          port: 587
          name: ${SECRET_SMTP_USERNAME}
          password: ${SECRET_SMTP_PASSWORD}
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: true
        redis.config.php: true
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
    persistence:
      enabled: true
      storageClass: synology-csi-delete
      accessMode: ReadWriteOnce
      size: 100Gi
    extraEnv:
      - name: OVERWRITEHOST
        value: "cloud.domrocco.de"
      - name: OVERWRITEPROTOCOL
        value: https
    redis:
      enabled: false
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.nextcloud.svc.cluster.local:5432
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_DATABASE_PASSWORD}
      database: nextcloud
    postgresql:
      enabled: true
      postgresqlUsername: nextcloud
      postgresqlPassword: ${SECRET_NEXTCLOUD_DATABASE_PASSWORD}
      postgresqlDatabase: nextcloud
      persistence:
        enabled: true
        storageClass: synology-csi-delete
    cronjob:
      enabled: true
