---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: dcardellino-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.domrocco.de"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      tls:
        - secretName: nextcloud-server-tls
          hosts:
            cloud.domrocco.de
    nextcloud:
      host: cloud.domrocco.de
      username: administrator
      password: Bratwurst2021!
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: domrocco.de
        smtp:
          host: mail.domrocco.de
          secure: ssl
          port: 587
          name: ${SECRET_SMTP_USERNAME}
          password: ${SECRET_SMTP_PASSWORD}
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: true
        redis.config.php: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://cloud.domrocco.de',
            'filelocking.enabled' => 'true',
            'loglevel' => '3',
            'enable_previews' => true,
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'true',
          );
    persistence:
      enabled: true
      storageClass: nfs-sc
      accessMode: ReadWriteOnce
      size: 10Gi
    redis:
      enabled: false
    internalDatabase:
      enabled: false
    postgresql:
      enabled: true
      postgresqlUsername: nextcloud
      postgresqlPassword: nextcloud
      postgresqlDatabase: nextcloud
      persistence:
        enabled: true
        storageClass: nfs-sc
    cronjob:
      enabled: true
