---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searx
  namespace: searx
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: searx
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    searx:
      baseUrl: https://roogle.domrocco.de
      mortyKey: bNJi9AtpYKINSi10XmVjohloReWxO5Dz4qNVohUOeUU=
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "homelab-tunnel.domrocco.de"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: roogle.domrocco.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: searx-server-tls
            hosts:
              - roogle.domrocco.de
