---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: uptime-kuma
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      PUID: 1024
      PGID: 100
      UPTIME_KUMA_PORT: 3001
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        ingressClassName: nginx
        hosts:
          - host: uptime.internal.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: uptime-kuma-server-tls
            hosts:
              - uptime.internal.${SECRET_PUBLIC_DOMAIN}
    persistence:
      data:
        enabled: true
        storageClass: nfs-sc
        size: 5Gi
        accessMode: ReadWriteOnce
