---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/Berlin"
      ALLOWED_NETWORKS: "192.168.180.0/24,192.168.178.0/24,192.168.182.0/24"
      PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      PLEX_PREFERENCE_2: "EnableIPv6=0"
      PLEX_PREFERENCE_3: "logDebug=1"
      PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "moviez.internal.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: nfs-sc
        size: 20Gi
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.180.21"
            path: /volume1/Plex
        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
    resources:
      requests:
        memory: 1000Mi
        gpu.intel.com/i915: 1
      limits:
        memory: 4000Mi
        gpu.intel.com/i915: 1
