# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:Ai9z9yXtKr3VodalgTMK9Nw=,iv:VwPouVqUvaNFJbD6LUDqJ2gAjYiRHvseFHcUdbkYu6k=,tag:NFpZlW/nQqKKoF1qeJ6S4Q==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:paetkdwnlijDnbR1rRzYe7PdCBcwQw70TnOYoc2WId4=,iv:YP7yKQHqDlOdFjCJZ6UFmz+rZOwXRsboFARF+GGHAUE=,tag:Vlv83tukeYbB3rWnXQXrCg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:y5NXNrV2yYygCC0UpY68YavDd+wXytWFiMl+F83+ulU=,iv:vHWqSAwdQc94bdCqYeo2M94IAHhEURPEUdjOpqC2+1E=,tag:YrCwsD2iTJXSB5mU+0o+fg==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:EQGjPiLP4+3ag3id011n1uNBHcWtAYnSFCSsrsHriM0=,iv:zY6/pEInYzDE+VsaymMCDZCxGHM33VfvxmAvXQeq+Ks=,tag:djXkZP2DpWw6ZFkBjeLG+Q==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:3D/hE9PF/TbBXr3SLzfaWcHBADohuE2/0r8bhcGZRnFUN2+JYfBEuBEjbmmj2A==,iv:j6gQf2kT0Dz+YFphFBIpu+smuhXhK8JLL4brvN/gJc8=,tag:sak1QNpUvq1IGKTQra881A==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:O6SMLuhLUcGdyA==,iv:lfliwRJ4JXxTLdy5sfESPsojBz0IMsmfQnSYvTJnTm0=,tag:i30wkt14jds0Qk7mirvAUA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:3nn2xPZuo+iFc0neqF4fUsw/OH5j6WgYLJ2UjNmFOILCe39CrEte9GREyFAO9M2w2/AB3KuujN7OuLwp8RyVig==,iv:skBnM/V5O3cSqPqK20PAXI2JLq+aeHNUJ/c7egnttpg=,tag:eVgTHAz/Cd0RDuGd3X7skA==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:xSySmJeo5X8s/QsIYhgIi+3Wjf7XzYb5pYrWoMsygJVRokQjlXcEeNPX6YrNYYw/EFErBAyAJxnOS8s9GUtx,iv:0dZuguh/gxB0YxgkWEW/AEvhYlP3N4Lx9jF3L4CsywI=,tag:7LfwURMXwL3vXi9hJrl4ng==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:2hssHOK6XUZka/1eYqgZRGJxGzUOigvjCLIeDwZetct+kY3nh5LDRANQj8Lopb/7CgI=,iv:4ZMht8Fg7yUQrdYD+LB9aKHUw4ux6RWPvlatglP3bF8=,tag:P0uppNKW4unpF+59zYzoVQ==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:HQ4K/EQ29Z4vA4cbQW0xrapCe0eUQg3PhwtCs6raylnP+owrdSuRkDEhBOtp2DHqXqU=,iv:AdbSvO0+jRk3syYgTKQEbLkQu0Z30oD74MGi7DVyNmQ=,tag:mytS2yRMew2OC33VVOeSMg==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:BAwawJ987pKGigOM,iv:dO0vTGvKwkNFci8CYZPclH81ABto8KOIwa6ecN9v/DU=,tag:TPIwqlQ/lGAr4PowI1Tw+w==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:Xy9igQQYCR/43RjrtTjCA75Puqetgs1Ni429Xh9tl2I=,iv:QhIJB30jkUWxIR55Y0RXeEXOBih/M9KO2Zd4l2uXGE0=,tag:B912fOiZz0gyJ/2FGJzKTA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:PgiI8vy4H00Bci0=,iv:Pk/z3zuUaaYYgtSA3ffvP8vF2iumAtZvDzjsDIgkunY=,tag:S3qlySK17M8axxkOK9V4Ag==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:ltlCUkFzyUr86zQiei0br4Q7cWMwHSojgVq2a+ZS/sx/2LLevSAC6RLX2fVabxMWpBXZmrM0s6GvioPtV0QaokxUUqVbwJ5QJb05wh0VswjV,iv:dGxpw0M7euTlNJw5UlNLOpz8zBbUqg203jvXiuyGAuc=,tag:E6XcsrcOIpCHltF7CglZiw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:9irYjiChhgOKwMaVnklILXGRPG5g2KWEALjxzxFsWhL4o+dZK+Kdd2heTCHQpXbh/A==,iv:yOcHjF8ftE9/uRRG9PgDD126rdU6bJ1IhsMoHkcEaHM=,tag:me4FjVObK2WIrgxnE0eLmA==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:/ua9dHiVdLLx/nXLyGLgvjkDueDkGcLZd6DlPTlrjK3o4d5YJmFFo7R3WYrTVpuOlSk=,iv:/l6MzJ+35bn4i5vvjrHiSqs02JTb34KT4RJn+q1JwQU=,tag:7OuJ1DTk+52lADXr/oNa5w==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:FOHVqsGt/VBfzcvY6cZqIIQZSynWZTOYnVZ0qUVmrIBMZDWYHeO7QUcByXJ2kb7IBfs=,iv:l5jrb9S2I5iCdAifR0qxniaHZ5iFCmOW3YQm2c5sIN0=,tag:6A2zxV3vf8fTeJTVIfZ3Ug==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:/XN4i97XhJcIKi/ZBfh8d849OTw1v13e5AhPdM6tk6w8KKuAaSVeqaggkn4IK0+heKY=,iv:Hu/+2oXsfgGWz6QkUosQaZiONQdB2TFLF3qkKuYQ/NQ=,tag:sYpndbo2dx5kP4IyhIfPGw==,type:str]
    SECRET_NEXTCLOUD_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:VNeF2Wdfef4avc9UhTcDYIOz1bBQoFJdu3/V10HqLws=,iv:2L666oz+qWbpnVcdPJ5zwPXMfJu7uUGcnzK8FFywBLk=,tag:pmEK2gMzqxI2v9xMATI7KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-14T17:43:42Z"
    mac: ENC[AES256_GCM,data:kMkIQ3ziDxfsTV3PLvemKdL+w0yhKEW8woiKu3Xor6jgcLHNqAIMvCfhnbBz43A1Xe06zV4RXxQrcPKKVQ7Nqg8PZ8mwk/PCcUcdXeHmVbqPnxJWJNs3/4H4HANlpMpKVnlecxS2kPFKugkdHtW1zySMEoRjSPwRFhHNI1gC7DE=,iv:UbcEJhErYlZG2iZH6tHjX7ftFutdd62hGzSE1LEl1pY=,tag:Z7tk928MXtoiLeS2R0li5w==,type:str]
    pgp:
        - created_at: "2022-04-14T17:43:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//V2I5MF7G58bKPBEm1+ubuQUsUqkctPk293syE+uRviv3
            dnXvHbt0KCc5u3eobPvAxTeguFeSyNhvM7Tfj0onkQPiig5LSTyg45uldNw30prv
            nCm01K52xmaWFfl0vqF+/j67l18EzQYKFLztwGU3ktzSfAdeY4ht5S17Y/zx02lV
            CmL/uDEXcE2Y3DeKUtacjSqRkh68/FVFvIE1Xd8vV0Z9MHB5DKsx3QiCtuVxS7iW
            U+xKCuU9EnkgJv348ZKA7WccBdIEYXGeGDZ1/hbV/7NyI0IC44EQVrhmXIccNcRT
            EC610GNvVcLhpJCH+oZI1qegTf7yE0YhQMrMbChNRRTMeA9FqapoCCXRSjIaBlXu
            mcJ5U6oVToRLxDaw5jCep2qs0hQ3JD+kIWByzWPUmEk0N/tmwUa4x7hLVytYEOxz
            1IfxSM7cCfftE2L6Ky28EaV4N0Az0l38dnGbHsF64/dVbin2KfiDPXoBdCHBhVvV
            QszSUm+VMlUUQ1jYTJSYUz7H64/LYZ0IUfNfz3vtq+7gBMIu6afkBB1nlc2XUMtM
            UGxz1rsbU/qXg5Z2D+wAGn1eK8bfv0tlszUW8QxIKj6Ef4FcoNNur0jVQT5xRc37
            cr6N7/NrPbDz4tbNtSAiEOgnd3V3jDV1FfaFA5JJg53dODCjFXt6IlcXGy4czwbU
            ZgEJAhDJtaoo2SxAr6EgXLGKTHrFJ6iBHq8e6vCP/7H8Wcz5LEBDia1UwoY+WyAC
            E0n5bRSuy/Lv79dAGb4IzQrvqrOd7zaARaD210K6mY9b2PjpZ5T18/gRgVh5LXzS
            R5/jYrHjsQ==
            =aDHW
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
