# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:uHOYuoLpWZ7LeswGU/q8JEA=,iv:Azj4dzujxAupHiXnHEIxDmI9U2tZ0QembQYAw2WD6HU=,tag:p3mMzNT3A1e4NXC5Iryviw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:vcwq/mFyit/VCMpdggDKFwvPEuvmNg1uVBAyRq7Izvs=,iv:4+DAotv0fuFetxWse2mEQCFxYhqzk8aV/+n5b632sXQ=,tag:EwyyF8C6l9iMs9qP//5aZQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:D+CbKzjmJpq5q/rTVxPGjobq7IUSIkVYW8eqRZTg3VE=,iv:IhWoYiwFSSx8qz8zSrEEDMd6FV6kWaqD7YuOPOBrMdQ=,tag:vocggvkTtLixYW7l2as12A==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:tzJAkSX8YwB4a3m/IlSqsu825n1F6/GEZU7OKhvQDu0=,iv:WgiNub0cBrevoJaayMMzO8JF+EpP+Hw0o0g44cw1aL0=,tag:V/E+7MBx2nPjaDgA2HJRgw==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:kbnlaXz946Lkoww4a4AnI/rNMmBg4zenSIFwLTkLG9ClJHpgoE0EBLwFJkBdVQ==,iv:8b1DCZFI2RTxh7x0nTdBd8XkrOimfqWOs3hzUtkps3Y=,tag:BrYmS+0+ksH/vZDccmQeTw==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:LjK+56cL9p55/A==,iv:39IF7Nii2nIZXkQd5JzIvrPGgr5McYLtYZRyXNQjJAw=,tag:oprWd3AttsP8IM/g2m4FAw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:gakf8ZSh44oUnBjFz9Knoprorjizf4JuxhAPEO1BG8U2Hvxe1cKeMu07A8dA2OKzZ87xNROn6jtLpXj5B15UeQ==,iv:PID3GkPYL5WLFFwEEGwsbfJCON95YQmmpsneRYgb9VI=,tag:uYRCJP5VFc2v+LLV+TJe0g==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:YmGMflnlys2KY/ifQJ5+8ACFRnw7OQBgmTujX9c8zJyzBn28ANOxaPJEYVnvqoa/5/H2dMceK8cb05SWROFN,iv:3ArjG3kJM/mIgDTqON8mVhL5mA2WQTPtYvlDf2Q6hZA=,tag:2tl+QTUIM0mGJ4Y/Foz3zg==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:A7PgUctcf9DX8S1qgj8HjM8NSGvLtmOdF9qEJnFYevpxPYzP0d32AMCun0b0UA3aF64=,iv:QQOvgANcDyWMBHCB2X9U2fLozgKeN7UaUbdQ4W090Pc=,tag:+xE4MibZy3+ZhEm7LZ52uA==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:qTigvPJv08hkeCw9PcVwqTEHX17rvzjfK6x0XYZuJ8ukjHQULoSVL8j1uo1Po6Nv+X0=,iv:fwxOLtFFT8922gK+L40qicDLIE701FEHQvv2Bx3QOgw=,tag:sEhBXGsjkN8/52JBENxEVg==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:DN6Xcvht+eAtxf+I/46MkJ+6ULEg8um1HYiH6kfjZsIgJa72P1xgTFVd6z7XQrlLceE=,iv:BvC7gcw+9byPkMi6RaJlN7ZLfXR+UEDu8IHjrDm8UJQ=,tag:j7NHFbMoenGiZQRw+RNUlQ==,type:str]
    SECRET_NEXTCLOUD_API_TOKEN: ENC[AES256_GCM,data:SEXNfiY7mm2xN4ByJsfyU4Px0F50DV1TrlVXW0J3bAhNsdFM5R34poysl6KRM/rV50F/u3Budww15VQnOjQKYA==,iv:yNBrcLRRoWrHe0/E/U3yXXiaPEUwOy1n+i4QMIVwqMk=,tag:7DkhDI4IQAsyrYh4Z4QngA==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:434KE98NUAzjzv/1,iv:SNdD83an1O9QXgAmh2KC7PLWiQpVovfP2Km00ObFB2o=,tag:sVtYrQEj8f09tJCyeub3Sw==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:l18pc3dNwtqCnJmJVTPsyyR40LyWQOrNIiGnX3yyN9Y=,iv:FfJDqVdFj9QnbYeKS2z+NN9HAFnoJ8pTRG1F+fWukHM=,tag:bnEUP7O4EgADkCyrQIY6Qw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:KNoydrfKUWMg7pM=,iv:QzY8QCgEm7ENHc8h8+B0ubT0dKPxAdbV6NZ+468bQus=,tag:+9M14Mbr8clR5jZnXHKfGA==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:3XtDzBY3XBIXjs9+OaILWr+oQfEICxWUJ8vEFJ/7oE0XlW9CC3q8M7JtSWGWN5idiFvCQDoQz6QMIwOteJUtlFIfsmaFobAHMfOquX6fd4Vb,iv:zjogvR+S/cn0oTMJwXcynLJaegvdQTAQqHOHcfXr1tI=,tag:Z4RE/tFgyejSeXgnUM0Vew==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:UUX8os3s/JiyEhiyErhojwIHYYWzbTWQc4y+SLxeR5RAQYAOAPi7KQlM2qT/tCUqdQ==,iv:SqbndPvQruUkeWnl3G1dc2MJhrLuctrx0/w4K3AdA+w=,tag:d2vopLkqfSrsUoNLI0XsYw==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:Loxt0Kr5D4Va0mzxSpqYMktooCOrXnEhiXVq5ifeLM6lx0dGfqVN1RwzIsTKdH1bpf0=,iv:BaFhPq6fTZNr6fvlvhkJZeANOmnHYAJPwppQV+5MLNs=,tag:umAJ/oNWXLuPzGGTsETr1w==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:j7eODVf+BxYwVJtdhrJXDZSJSrrKhVm1oFXi9xJWNqlDZISaefmnxGIei8hv97Ci/kc=,iv:5au3wKTNXdeUisno1SxZnATTpyDxHMQvAISOQLdMUj4=,tag:nRE1LGybQghenzHouQOuEw==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:O39rPmy1xUuKbzbCxfTl24ICplhHddx8FZGlm+wUtdUFRWcgr00ZeU1CzG29xvAwNAA=,iv:rjfKZziJainEKxsIe9W4VSgnJ2ckiq9FASsj9tVxChU=,tag:a/ecZuhJ/5XX9h6dJYwsZg==,type:str]
    SECRET_NEXTCLOUD_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:/DgbX+Dn45nzaVNG7/o+Dj+qwfUkaLwrpXd7C0v1jEE=,iv:rQnF/Jd2DOfAF+YSCyF8Tbfq5P9TQWXLajdIzyZUuBM=,tag:mhFutiMBsEv5r0SgIazy1g==,type:str]
    SECRET_KURED_SLACK_API_URL: ENC[AES256_GCM,data:eRUZUDBcxXH+f4X/dWxcmwCeAXCEFddxGPzPvRoPkRsa8ZSsENR1ByN7eXqJPt58Sj8gqXVJ51UcXf6xa3i5a0L6+dApe38LDHwNb8qx134Z,iv:w+1wo9Qrv6rrMVT6IzDk4R1v5425Bq8eZL1AU+WjCXY=,tag:E3zbiwPjqeFo+6jDUxRgQw==,type:str]
    SECRET_MAILCOW_API_KEY: ENC[AES256_GCM,data:mWV2koplOzCEU+38jnUO05zS2kCb9IPIS0VXM1j8jNj8zQ==,iv:cjVfP7G83k4cHdZ6AtrNRBLb3FWZApy9gm1eXuuK0XI=,tag:0m5Bl0gB6+hROJuesn54CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-27T11:34:42Z"
    mac: ENC[AES256_GCM,data:hKmoZYfmiRwmnILyu/8Yr5afSHPVAcpYZkTEPoKDHkBcoFJelJUjHcOE3etxFJfAjYu0rVGfRtKgH2/pKSq+depCGvE0BQ9LrO6+45bJGEgoUBkoF4UDzBZoAnPc9gJXh4zvv0lAJveTE1aiPmvCEIUj08LzFLjzdl6OPnPvfPY=,iv:0ksoAYaCSTG0CU/LmMAhaNf2b24y+HI+K/fT9BOH+sw=,tag:95hiIyaEhRWk0NzRd2K2rw==,type:str]
    pgp:
        - created_at: "2022-04-27T11:34:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ/+PbLeDB9kBKHbmPRLVCMk1vCiAS81Ul6w1I4rXg/yRA1S
            Psr5AKl6NXbTDNAO0SAKWoLxoSkyIyBeK8GOv2yePUiE+DbHIX696MJspeyMLizf
            yvwK3yIPR2k3NmH+BRZyG+T3p96RkE4U+B0l3fAwZgmA6mT1o9ePZsVbi+jbiFEW
            qp93LNLhFM4GqGtLacMmRnEzoAwLSo1MtAclYq/3ieuUM3QVrSwUc5SF06Jfq9IA
            K0FlZI+YvVL2nz02W1VWs+5HrTqb3y7z8vuD/iczqWgArXg+8dKpZcso9nqmtGCj
            mjTQl/lLv7L0yexhrLZzdHXBgjpMHTpQV142da+siOiBiClqssLNBCAEFmtrt5qz
            z6MTUW4idSsoMtBWhV7oYvZbouR+hobMzRaQQfjE7+AuH6jPXnxiq6T69vz3Cfl+
            Ov7bkgmyhNqt0dHpsSvfQTrfxUDCDsM0dGguoe6ApaRHtvra7mZtH/PPqlTgrEKe
            L33sLx/El3nhjv4GtJMeSNtcU/DG3l1rqum4H4K7oevvaMaSSZYDW/QQl9tnOmG9
            mhfGGEsenxmeeLE+k+HpN0d+7PZekrfBMpMKvxV2y6AndDbrYm704ay2zlJTUvXN
            HhZCyau41RudJgCgP+9lm3y3FVjFgLIDN7ZfmfLADzUuDr/uRgL15MTvLi09MojU
            aAEJAhBKREhBoge1hfZg2lXPuyDZAqMFi72eGyrvIy3yafLmqOL73DB5OM51JC7P
            CAY5nlljuzBzbfiSjyGSCnkl2Tyu9SGA/09fn2O1AZrZgRRbWsEiq1jBxPGZ6nnT
            elRhBWJqLqcF
            =HcTL
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
