# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:HAqSoW6aEHiVZeCWO0mSGtQ=,iv:WCSAuOKsN/BWaabWZysIYQ6fw3bT6IK1JdFnybJDzrY=,tag:3EjNoPzaHumdmbzxh3vRTg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:0utNLamY4HneYR0bfxyM89oS/X7ggm2kk5kgXsLyOS8=,iv:V4Cq3e07VCz3yXV1XFtSx5ve8Mh65X+1YgIC+v7SoGg=,tag:fx8TtB25OigdB5jYOrvAfg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:97ZSAl3x0Fpf22zu4MsoS7I65pPW+RhbTF5vZqWrYyM=,iv:JJoKgdjDCnKgs1ZyvZzS25jC0myS9gv16D2rFH+gZsI=,tag:KrkhFRrvh455QH2sue6v3g==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:hpmQQjoQIoOQ3mnyANmBod88p/S6K6oHq15/Z72FNFA=,iv:JSuxbPgo8sKlB+oDimf0kH8VoCphFWhpr5JsWyNybVM=,tag:rLCEXT8Q5hMHg5o7x4UHbQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:1FnLRVtzIG1pAD25fadpF2RZupAcyVr+GXtywbLmzEzv47VDYwifsdgEjeETVg==,iv:7UimTtVovgkbt9yz3/GtObEes+ciFfqfKzfpjCHWFb8=,tag:KKDGJANWDS2WBTIodH6wNw==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:UO7DMBFryw1OPQ==,iv:WG1chlx9RF0sECTlntDFrw5BOUIKLPwEKZF3mrPRAbc=,tag:+jYAY7BaR3UpLVzOeSYtKg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:u4qw4GMrMZGIpQpHP7ls514BkAjsVd0z6yN9DoYuvhnyVoz+SqP+CKvan28b7zeLklNyltl73cs0drl6s50LlQ==,iv:UiCOKyeqDYVz1wc2JHVe5bISLV/4umWlw9T0ZVts73o=,tag:wFqgi0Owz4kGxwWQr5gylw==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:NaZVK83Mb13CTmv44p/zCk4Grj3ZoPSIgDxOXrYbrVTBv8iiQuNZVz2uECm1TmrRZN/Tc9RknSkl4D+MGt8z,iv:XOumhsLzFdWDKJOjmROzoMsP2A5i5bQk9SXRNfrDV4c=,tag:DiSp5A+bmYPmYWEyz8Idpg==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:X1UlaHUjZf66/XfuQ/mRC7ktaGcKwcKVvXLjllMd3IBnKCrTr7ct8KyTyZe0KwKhYek=,iv:KxXXYCSBQ9azohgVjSHaW6/9rCEQhYANc5ZKLeKfjF8=,tag:OGGkNFZ7iUBhi4bRDWjAKw==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:Z/wZk/U4y7jxU6xj9PGANS+015xvsRcit0rsXqsmpT0hpWMgYMAVqXZZuR0n2WHy0a4=,iv:hcmweOlHHmwU5sYBtHUPuJ+ArkEzTcwNkL8S6iD7mj0=,tag:w8Yz6hFLkcWYUjK3Q2qxfw==,type:str]
    SECRET_NEXTCLOUD_API_TOKEN: ENC[AES256_GCM,data:eY0Y/+TKgxzLzYp37EGg4M+KU5dOiea7pCFtdx2L9g6JXyZfk8RpDCHzORcrufdu/5YDKzD9F1EnTa5ssDHABA==,iv:OnUYHx19UksLj+wQsLxTg0qEriuOqrj757tHkqHrJgo=,tag:pxMlNruGecIAy8CveRv1LQ==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:O5zbGN1kAfd+mVJj,iv:wX9Pq7/FF8hfPqsDIpqbUl8dBfBNkPPBsXPO/41to2E=,tag:LYaQUQbs+IMOWjPELJ8WPg==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:YRyNAmKn1nP0asRCWAB/s/fFDWtXeyrEK1319gt0ANk=,iv:WIjYkmyRPlI6DM4eM9vF+QqzoGXBZY+pxbbi1EUdJcY=,tag:kABE7FRllWvONdabj7wguQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:MRCsBx/XfP5ijJ8=,iv:uEQuVT72aX9Sp2k8W7n1aRwe3crf4OI28zppY4T4Ymo=,tag:mHGlwretYUtolSSomA7dAw==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:wlQ54sPW5iZQ+cJcAT/YcRmgjm5mOyTzCxesrTY8s8g456Vq24qVm2m3khoH7S0wDQxFAG8mA7EXlINGX5QfEzt9e0cirbp4IZO22ob187gP,iv:N+WivNqEA/kk8jCpCznmrnDZC5Uuh6xDStUmSeu5XKY=,tag:ku/QeDcj6Xcb4LNDyUikuw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:46YKFRw4DmycSoROWCfB+TlxzjRa7FZrXHoAj9JIhFyls92+6Vas86Q7KcuT4UuOSg==,iv:yVtZUrjWwGTLr2RgJsWqIkZ7JtS30w0MRlq6kFXCaIA=,tag:+GlUmT9Iz1VPf44jZ8aUBQ==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:WEutCiFi4tGjt94kkM1UzKeXFDE/WUFrSIO8X2ck7d10BBE2tKw91Y2yMmPq9fJqmLU=,iv:LU2IATHEQb9tBSdEAySfqEAfc+gegLWK1+UoIixjVCQ=,tag:9YcxmussgZgC1XmsAm0pbg==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:mYli0MWoTBJYOR4Zo53ILWLzCYj7uCo5/Kfc4dlojqYFU8CcXexgGGwCO7vUF4hkXoQ=,iv:munhbW0vjBhsQOd5kkE5XBvL4jr1f5brqT7zhQtKs1c=,tag:fY75y5StmlECWfisLsw+qw==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:lVzuvss3U5der/coP5Pc2yAIM19w4gxZomntl3rbuwmscnimUCKm8Eq3tZSE71sZjjs=,iv:cXbB9rLbhaEwcYE0OhGfOQQwOy2cD045naEuWovh3l8=,tag:mTv23gRWD0JmnO5uDvjs8w==,type:str]
    SECRET_NEXTCLOUD_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cj0DpfypR/YvljWCX46p23PQ3u+04KuENEAqHBzhSvw=,iv:p/VZxKefzd1JTHQggNLCQCQpvkXaq9w9lr6MbiJlfOo=,tag:SvAk8PR2BjjzMpXvUHtaVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-15T05:25:59Z"
    mac: ENC[AES256_GCM,data:8IBzGNbe1tJNZIjj838hKdtBylh8QW3CWWRy3DDozgm+KPVT0+IDZWiWGkXR50P2Ci4Gdt3pcbSumyHa7Ev/xglD/s8PrITTY/WJ0aieLHRWw8euseoOQK+nSrbjS8mTjuAuDpYi4cFKIUgpBvLM4h7ibsgGf77KmT+jfxGLSg0=,iv:IIJXzUh7684dtnNyhD7rHpeThQLTNcOLhHgoc3BTnmg=,tag:/Dp95lfeccmPINICRvcllA==,type:str]
    pgp:
        - created_at: "2022-04-15T05:25:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//eTzvplLuX74UGyeKLaJFVOT51NB4EfSuyt/ienTIMnQR
            Ib3iMMHuwKXryUvB7Vo1ZH7MSGwmm4RCU9tubaITbsN2ZYJcNFNGOXdhwZ653SNm
            qGBLRRWJlB9cU0UMz+7jP1POd1TVPjJtW+H8gkJFUYR9dFH2upBx4yWrM3YYobjl
            SHzqX3Zc22OhBuoQ+g5tjafsOZ+9X/CxSWutS6ePrH4wZ8+LMbYhLZ/Ty/KYMOHM
            nMC6O053UyEtiQVAaF75TcQwPjunU7wc8XN8nnEhSaYqefxA5OouRYbHDERoP/h9
            FtEyp80GEIktutSDK9vWjp6Ixb0fOnr7ox4lKjs40NME22YzClO7YVxz/jKOfe00
            8+AmDevfNq8S3CpzfzT5k9ObcZtJTk9Ifxyb8mMStZwMwsiE/NpD/x2wsDvS2OOD
            60C03GRThNL3upTOvG8ReEeY2bDuWTpBiCcqKhIC/kiZo/VNMNgGAJ5T57/DPYFW
            pBla+6qNILcAbdZ3ZfJ3G649+GRUb8As2Ts0hGVqMRAGyx3kKHr1uv20IfJpcwsb
            5QglFxO8Np3rfbYokjphSBPQxJO1oxDX2pk0o0Vc1N37piIk8y1qWFsuvPtW2RYl
            Wk+sSIWdcntDrAohsE/B0q5zl52ulutN0nWKSUU2kuoybo7PieUI8w+d64WHWPvU
            ZgEJAhDqwWkwh7WdhvISwiTGMuK3VXSkj5gP/XWi0/czioCVYJkQzhnI0Bpz5K+C
            /rZ9y+6BeeU3XNtITTJEhLpW2Z2tQI7343gGdeFxiUnTWZ/jE6lCgY1COQMm/ML5
            3h1OPnJ75g==
            =B5xt
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
