# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:jwE+/7t3B4T/saYUkR5lA7Y=,iv:/U58MD/5BFFvm3sokWF3tytJmJbB1bY14J02GL0qiek=,tag:DVw0JJ5L3OizLR5hjoMBqg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:JfT95KIArx18TjxoVdcqsCAFQK/b9loPzOdY+AMxPKM=,iv:tPgiVBLhEoHOXix03g2Eypw2E/LdKXreKCYaiPW7Sns=,tag:y5MECFrN/tuVeuuHvknc0A==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Mw1A6nRwvq8uWxv9WNrVvZXRvoAn6A8bq/BoR8eTJ5A=,iv:C8ESqgGTovCMlPQE1Ww8l1iffOJcswxu0diLIP4zKjw=,tag:hWlKilcUxQ3kh35P5/pW2Q==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:oIwM+Ot7jXzSxtehA4AVb4hGZ7SjDc2nircbTs0SZnsiHv/Wxdt0xqG/R5W3AA==,iv:ZQGOZO9p4EPgq5DztNasZI52yTPIQtY2E9lnIAw0RDI=,tag:1wDt6I1CZ/qJjOx/Gmii7g==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:uGzdeAdfEroYSg==,iv:3WPFT43ImIpWb4PUvvubgZxCvMooptc2v61760fkSMg=,tag:g0XpfDcSZVWRZstYWdM3LA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:bnJDajVi7yhbTo8Pn+soLQhA4xuufaQWzlMHpMT+T5pER1cIWgewUkQaTOZkaH+0MEKwMH9w64iOhe1fzVEdoA==,iv:F2Wk9G/33rqvx1RrBkVcngHdThKbVytfkqVPAXk/zx4=,tag:zjbFIKv5m4llQ7qHOCeNtQ==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:LgCEuSxnFyCD+HbjRI1Mke8h3plsP9H/DLmqljQau1EOOVhXYI5x/E/nlinr2jbWX8J7qL3ETI00oHXe6Vx5,iv:pwtmE7CIKZk0cMVA2QKgH4U68OeMT5mRNnTPEO7VCqE=,tag:ISs9UT72dLUIuBaE+g5I6w==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:a0WhrJeOvoIuC5fO,iv:zZWmYezOkiDiMibVrcGc976ZPywoy3/9PeSdqh18XZk=,tag:DBggx2FurJ6+UEW95ewJVQ==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:jPQgBUOJXZinpBbQVXYzFg6vZNpLggDm3oFwnUHrK58=,iv:x7kzL300GaglUq5pVlMC9+8ei+pxvshdZ7SQJdpsKzQ=,tag:n4nNJ50mYGzrUTtabYbmdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-10T11:40:05Z"
    mac: ENC[AES256_GCM,data:R2TVBchplH2rd2ityudxmr0p/re8lVXDk16y8i1y3wbhfg+6FQ8ESeqIk8O6UUno9gOBZnaEYlHvuIk/tp9naBNodutDDvsfC79Tbmc43cOtE4SNyOEb7Zf7v9Z04XpNVyegUDfli8N2DMqRZD5l3t4Rt/sj8YyiEt72sjMLhaA=,iv:OfA7QOpTaOMgTGKir2LaYlNO0pdbh7ctBYKB0KOJ0wo=,tag:PelWadcpq/fzxUejUPi35g==,type:str]
    pgp:
        - created_at: "2022-03-10T11:40:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//d9yLq04NpUmG315GYxoLc7UOroocEBw/tBfpohtLEtyc
            EG5zzFk+7FoHDEFkCD466wW2N63m9s5U4t6saGzydbERhw1TW1x7m4ZSfBXPd36Z
            iEFTrrty1NHJZ+6UomQjzgV+Yk5TaTBW7dx0cSm84zfBvVW+J9tFWCgLApCWR0IY
            ypzsw9Ewgel5KUOtQrx64tDCYQPeztO2oTbLk0npHsJ2OAhbDsmKEaG+lv2K2uWx
            INcScvrBj5cL+XzHNVO7TZilUzG3jokeIAkvv+uRrICVYLTSgtBGHo65ODudRzX3
            PzLpBosiCySuL2h8X0uk+yAKyvH6DfWQ0/jfWcu4qvhcxlnAHOJ6dOhzokaNMgwP
            u6YWUDYv6cmemjycKsV/CAm8IWPoXp/RCFn2Braaa1tVk5eBxCXN5jLlMT3GmvVp
            BhWY3bcKMvXaE5AcuQMpLhxJtoeAPFejs0dX1wQASxp2hm2DceENACNXD5NwFCgB
            nvYO4sLqa3tcJoRYc1V81cjQexvgU79q155jIou+/dIyanTvvstmd70bfK6aXNy8
            hqcRo8HiKE3/hMA/riO+UNYWkEUhYrUKmg5wb1YxNIfQH3ZSW3MtIi1hfbLbwz71
            IXvK0WxrzC0vQBac2mWYTlTGBbVpyiU9IQpgDIeH1PfKheEyaJ4T7rfTmqjWLAbU
            ZgEJAhDVMrjj0QJ4WUNOOL73ukNvDVQHKGntl8SqDY2X1bkJs4rNuHpZ5aRYQidF
            oew8NjLT6BmdqzSL4pcUGke8IeA8gYGfVh3J+orsA/j9WFPXcGWxf3+DJyyFX9dk
            k+ghKGoYEQ==
            =ogTt
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
