# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:iWalyq27QxCxyLXskUulZpA=,iv:WnPvk5P+kSpW8vTcuneoaQ4uWrzJm99ZyU8rpnq7tE4=,tag:45g5Rslhuy8XqbebwfojPg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:rLMp9vZwLaXobEtM3SkXKGUXAKocWdtMnGQqgbWMCP0=,iv:U8JqNPwXu96AzzON9U5sm5iWWpE8VZ/8vIuE2DD6hPo=,tag:E0oigcBHxYzm1R3Lwey/wQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oRk9pxsiqY+ak35y50dl/M7KCWPWVkEMmYD2E8P9QGA=,iv:fcn4RmxCk+do8+A5iooXKpJiJjWNELpVFoxdqrqEreQ=,tag:p3nv3gCRDK6oLRW+/YHmxg==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:OIkUVq4lWw+yVL73hBO9CA6Gv4Mgs1aVkOtmhnOqDGE=,iv:jeZ1cRPys2H/Kr0oVLKz9aDKvPHkcANI/1+2FIlBaVU=,tag:56uxFcOlmUhx1XUMRKYUdQ==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:yeEsacXut1G8xCzOfHVZsHPbxlt3/8PO/ARg2AOUtvUsY/iIamV8LHj7s7e+kEZ5Kld3aPnogfOnumj94pqu1A==,iv:6OHfS8H09o+WKcLkS9/eE4p0iiHNDZpSOEYLcYK6YfE=,tag:UxC47I+YCV8zT2ZCCxpzZg==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:x/S/NX4MweNRipRbPU/Xbd23XJzq5WEWZ+oZ8q6s+3qGItfDTwBdVsSE65O9e3nxNj01zxCRxfIIwSPR6WSJ,iv:1/KZryKRTyL8GCoy6ncg1NVzdDQe7JC2b1BWGafdxKE=,tag:+xoQZpnXfhCOaRiiqyQiRQ==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:xYJ/FW+Oa5dlGMu1,iv:IKhtjV6Ukg7S/v97BoaoXws6+c/9PxYrazcZZ/shIYg=,tag:+/DlBzo2IlOehusbGEc+HA==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:hX+dgpcjwRzTp4CIwVedEea3hMCv+CzNjhRp34ZnyU0=,iv:41RmtlhrA0eLE2pEiL8xcQ/XO+1SZrGWmkDx4WzyMjs=,tag:KPc3qk1GxBywJqvONoxRpg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:ac8gZEXSVVFhCv4=,iv:yDHeYkqPYWA9p0qC3vr8bbkR02NgIM0Uid38Yu3Xmpk=,tag:RR9OFPpb3ytnNlWYJ+Z3FA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:yva22SH6iKtCZBm9,iv:b596omSYEf9LnXm2h/qeQTGxVVBzgynq58DYxluS/wU=,tag:56b1nNPMdO8j4gBJWW0EuQ==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:fGIZ84c1aRAcU6B1XthMonfor5jfIqakj8Le5JQgGYJhqKwk50g06OX+b0ncErFGEgVL021SrOoc6aN1rnz3tS8Dn7aMeNb6/6ag+OvTrzy2,iv:M9KNw412rrzzYTKBfrVgCMAuoEoR6BQYqkaYr2qUS60=,tag:ZOXZDbW6IHJr2BTY3TFF+w==,type:str]
    SECRET_KURED_SLACK_API_URL: ENC[AES256_GCM,data:FUGs2jMPqT4FFKOvCWkhSQLeDeuP3vK2i2YAFd2NFya3KXU3p5qsfXm8T1vH7ro/xvfDCP/XHxYV+H6fpryh/aUIN0OhmE575PecnyJERp/t,iv:htYAK/WQSL9xVMv140/pzASv5OnM3lMEYtmq+ac52WM=,tag:fPbTgA72zTElsXP5R81fbQ==,type:str]
    SECRET_MAILCOW_API_KEY: ENC[AES256_GCM,data:CMaPkRb+vo+TTy/lIeMlWJR9u0Bz0hyJVSlN6huxonvjNQ==,iv:RPwU2GDq0NvkxfcQ7AD0JQ2xPMex6jXI/iT4jAdpZTo=,tag:u13U+7qSzaGg1oO3LvMAvA==,type:str]
    SECRET_OPSGENIE_TEAM_ID: ENC[AES256_GCM,data:ewiWWisPuo0Y/OcF2YSi1v13ymUbB9MnBAlaUXYI0XNgSWkj,iv:LsBwohb9AJNYzsMRNHPIm2DUrwTZS7bs8xsJbPs/gX8=,tag:qi8me5d4Ld7kIigx1PjYfw==,type:str]
    SECRET_OPSGENIE_API_KEY: ENC[AES256_GCM,data:Iq/v5aR55/jFDEktxjIdFXnF1GkdbuJc92thgjlLo0evK9gs,iv:7ZCZ96ehvyeyzIm64Y63ts0+tSsMO6fnA7v5wlIgAcc=,tag:YIYrRQMeZDXuU7WaQfVNKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-17T04:58:57Z"
    mac: ENC[AES256_GCM,data:EstchgOKBDsY+4w5jVZQ4wAzaErJBJc2I7gxULHDtC6poy9ld0P8PHVG9nZyIs5zlGnmdtXTWtQ3kGDNkU5ezxT8JCxY3o++4xahRopi3Ee71bIm+pDtoVljTLkcicGH5sbobMBP9r70KoRiqtVcdeU5AQJgIjNkSztM1ZR0cvQ=,iv:rNycJK4LkwJxAnzg+8ip/IQ1wPfX0goxOxC67Z+aFkg=,tag:e4uLOKAdGcNnqtHIxExEng==,type:str]
    pgp:
        - created_at: "2022-09-17T04:58:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//Yib9VdF8mzSlGjhWblLqXTdpR/xEoz6j8+qgi9QFzDij
            87apkKUt6i5dMfRmWk4QQLjxnEtIeUReQrMvxhTVwJ7x/6k1AfQkFvxAsI5X/Jng
            NqqgS9zDlYspLiO1L51I78nfsQoyRwNDzZq1qWQ1gstRp97uATZamiUqG9leQCXQ
            nUtWKV2FYOyYfZvTFW0WwCPBjsvpVmneo9U6WT/dPvztBkwDWE2zPHA4EYz1WTB+
            gPbtK40UZeVt1zzRsen/y6kpV+35N8R8ncluPLKt2VcKveLHLRqlEZhHxpKnuemc
            oaciu8Z9zz8ZwpTgk+LvsaYEpNKgWoTVEVywgnc2URmhWZ3NZthb6x67jmB+2uK9
            gv4qNqD4bpO8utoJNPUwjDmh+MlzMKQN6arsi7Q3QlDZ50wdqiN2b//KakFyEg5V
            j37W4qBNwtsp+cMA5wwO1jrABwru/Wz3kGTgt0D/6M4yJ1+4lPymiuPQOZBxxqv+
            onUE3K2ofFdJ/pxTmCQf29zHMfljW16nHrI85ktja6trUE/KSpLaAeMVbQ2xatYx
            Y4EdyNHHvO/Yxrfm9M46Uwu975eqgTOUtVVaxTnRsTMyQLoXxEWf5dbHcpmiVwZk
            Q1fzg+4jEd3CeJmuIjdr4jN7LZX8BVVgEaNYfgEgvFzj8+s+Huz2binZbbDUFlDU
            ZgEJAhDHd+Vp7WDphFAdwB2ougu1tsDnhskiIPARUpPlwfF5ala7FGoTmd7VptaY
            +n4ibtQm6L9E80hctVY4EVjTCm5pk12ZrjkvKkQdan7Jk7O8cLLuXqgXX7fH/ysR
            CWnE7aq9Xw==
            =Pvq1
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
