# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:UH/Rc0Fez1yWsGXZewTcDGY=,iv:TG3LFhsXcrNJ61MhPvhONVrDeGXuG8V32mlacfoKlcY=,tag:diZLHngqNQo8lTH6SrMKqw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:EI9Wp5QU5cv9foVCZ3uddVD87bwfgDavTvQ7P4jt66M=,iv:eVlUO3Xu2qObqXd78lDlljet8iIDFVMdpqfiKP+Hkq4=,tag:/rVcWPDV0OfStYK00CLbcA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:X/Kx0NDFRmrk6he4bCSey5Q7E/OVJ2K3o8It8k8YP6s=,iv:vs1sROjBN/1lXb3MCOlKOSdd+W5RGJlPve3cD4fqQMU=,tag:aXyArq6YT7IY6AEVGznGvw==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:hdDSUY90WmHKVubG9XgHsTIDXqouBShcFe7r03XUuFo=,iv:dt0Aw/8W9x2rvIhx6qWHUJv/pa1IgUI8lPTp1wf8AW0=,tag:Vazh2o0j6huPxoCBENF8JQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:Qfjcasrd27zpJU97RMO8xJq6T7TxfAbXAGGIcEHrReWNjnXe4EaSbqAHdH/ntQ==,iv:KFoLPQvWno7UXjfWJpYraiNl5nxvDkDI8moCO9pWhIc=,tag:lnJDNdqzSupWSB8FdAAU6A==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:Jbp4H7SmgfIPgg==,iv:fju532d2Ou954rPhoM6PtJZpG4o+RwcC8T0RQ30W+h4=,tag:Y/k3j2Ffej90mthSuTsa4Q==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:DK44+rRUa5uKymq5m8lkZwekO7sRt9D8y5He9k5duZl95eCI0cGH6uz/VRENKNdRZLLr32QbEJBB4ygA1a5y0g==,iv:aUDV+7fHT+uT7/CH/vBSEn4wdc9gN4G7FRXqqCL2Lcc=,tag:8VYhgrWpA8wy4RDC09QlOA==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:rsLpHv+xxnDwD4YO/t9xbRxPjwnctWn0Sd4S0NM9wV11HbuD67tZcv9kCLsUykLbQ/I0egk2xJrdSheMDxCc,iv:wqrxbQQE6c7RA5DP1aHLkbmWN34seXAIVIxbio4F4wQ=,tag:B4f3Mjh0F8l9xW9z1p+yww==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:GjkFtZQeFYSyJUsGVeJsvtsJ/oI9yq0o4h96P5tNyltL9RJwfpOUfBW32Eh92WXd2rs=,iv:kUHbAi+nS+ZC7+MIV1S/SfgID1w4Y85vXC/+FEGDy5s=,tag:BKxeg7uhZObb2efoX4AIsw==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:bhPhPIvFtbQ1SalGNIPgpQppHNuu/MxgVxRTjnqMnO8rai0TZhTRDB5vPSAIwEcKVJs=,iv:jnXyy6/fhu2oZVmNZ/FixY4PRXJL7FPXVaNgk2/5TP4=,tag:gl3QEBPiRBYycdPqpjfdqA==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:od5cGSy74PEwdGopSoNZPI6SC5I25hIceNeSNNsPDibVJhI0aYIqXNj81FWTKcDYFts=,iv:Vp7Gibkx5cMa9zsLwimodOa2/vt/kR2kplhqoQhdzu0=,tag:w/VIVW7hrNpFSiJgiN+cGQ==,type:str]
    SECRET_NEXTCLOUD_API_TOKEN: ENC[AES256_GCM,data:c0ALhQ2Vr0QKb//bQI0eZNzoe7UGjeQNVAbxt9GB/DwZAQUsOJcVKzbSCqQaN/yQfExQD2AH2MH74PcVpiKxLA==,iv:IBKbNTnU+7Pxe/AQM9yXe9cEeEnW8eyh5iFWF1BIhvA=,tag:8s+9xCV2fuNI5MR7kiYrUQ==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:JSy6JQ1y7aW0quY5,iv:UFVHkyheN8fRyO7R3fWSvi46uH6MbZ8gwdJYbxuO5TQ=,tag:APrk8nzKVCvBuDolHojSxA==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:4NKvSP+RHUfsvrebNJca4xM4umldzxg3/ctYM/oCYL8=,iv:EjnsCxG5MoDEmzmVuI/fWWHdxlT4HIixOgGpgkJGHl0=,tag:2xzQuuj5UAVfrgsp8bBK+A==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:YE/OBI7PPO7yDM4=,iv:+6vnbWFIW3D1cft4BSXOfO93PLeR7zJl+rpEeP3C0Lo=,tag:TRbwK6xZHi3D073xEgz3Rw==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:sTBhbcBaPAa1XaCEoVfDIHxUDVtMZln+BOLWKXqNb1ZPyakgxtfe1m62zb1bOPa2T+7AkzwdNUvGNXM0pxqrSv2C3toIpHoojeNC0YB9dqsn,iv:jsm20vSNfqBV1ha/pGG6UUAF89mdRxy6wjKwqIekV3g=,tag:KsfYInjoiozSasEJN19HIA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:dewe+JOzFFSmCrsU0AWt5LNWJYuTcLdVyYy5s/1jMUicHdbZ6R6NFbXz5eGqqjQOaw==,iv:CI4NF3EOhcmiX0M0T9E3nAAIznH97Vqtp0tnr1vSDx8=,tag:ZJFLY75A9VuSecswTT7KPQ==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:nLPlTLOR+EsVvt8nu10Q8PaQ782DPAJfFfwSxbJU3KRz0f4xc0BTZYdox32BLCK4Gnc=,iv:iBQ9pRuRCXib9b7kXp+Vp3AZz1KtSH9MhNlD1lXUoT8=,tag:e0RLCY4cLOOEUUQ33UZbrA==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:7IQYgacLpKh06yJh8qJL51Tam/8umGmUQqfNAsPSB1CCNjJGc8dykkMKEaIf5rp1WZs=,iv:kh6GVqYxxsS8NqrpCuTGR7h0wqsbxvF18a94yaIOKOw=,tag:azTNCOA2aStTueisAOAuXA==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:D0TqjOAWEcJl3bn6YP5ThqrHRf2DbFZ2IMhFLpZUorf1sJlRX6VD+vTGQPxQYqwSMKI=,iv:qEdyj45tXMuj0+ImAqlNHtRMLW04inkl7lQgQkErGfo=,tag:Bocffc/ta415WVelhHDf2Q==,type:str]
    SECRET_NEXTCLOUD_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:ve9KI3U0lnrCczOtmnHwaDcwMonaR0hWnfBtGWSLu7o=,iv:0qN1AcmyMlbcTEj8AHHk4bVeIsOvydgzkf6IneaZlmc=,tag:BsYUoPGr0M4Z5SXje/Ihow==,type:str]
    SECRET_KURED_SLACK_API_URL: ENC[AES256_GCM,data:CTgJMtYAheLW9YCelkuzqx2H//ODw/46ModKrpYsW+rLvwbsmFP8zPuS24VLodaaJI+7xDk09c5m1R8OxY0OMt64hekA1kc0n+KADVYBfx5v,iv:EgHIVeNP+zQ/aglEqZHbk9pk390GTwo4PW4WWZODu7g=,tag:VYC59ShrcU5yJ63AHNXmKA==,type:str]
    SECRET_MAILCOW_API_KEY: ENC[AES256_GCM,data:XyHzfHHdg4NneeyDY5SL0gosqNWkAJurVuAkBE4OMarkGw==,iv:ibGnSXXH0E7J4zfNqqyippBor/Yl+kJmCi25tKNNNwE=,tag:sLwz+nsBRM0it1GOhR6Lxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-29T05:23:24Z"
    mac: ENC[AES256_GCM,data:/AyHU+HDB2GVWKnf88n2k2ZMbQ2mzurH135ABuzRhHSoz7Or73r1GlDCmzmvCTeVeU06YqKb7x+9dLB9jipaFEkYDJdBUTyfNu+1flYACwTY6QPiXAjn0XF+QbfJ4JaS8fGetXge19/9wcm+Who6//iJKpAZ0dwdyGNgFrOyQkQ=,iv:/7ri//c7Z4zsR2XeD8/ueliyIyFDg8ldpcqMIfoH+Zs=,tag:xu8MBfR9Nf0+RLqJPvUSMQ==,type:str]
    pgp:
        - created_at: "2022-04-29T05:23:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ/+LEwkfS4H8ZxieJmcosKgIrq+rop+JKe83d7C8dLEr7vo
            8Wy6wvxA0xawkj5WOcqhLxO6r60tgNU9TNITK53bC6GLjasFxeCJ/DGb8Vp3WKqG
            uzhGnR8cPzhOxD3cB2wbDeo4uV4rR11uRVEWTr4XdV8lo4ATOu4b7smruP3xxlUi
            Yp0Z1g0ssi+m0P6ykFR23qpNM5OQqrYv1zzZm0VolqXVExlC4vHdfSSHi0hv+pZU
            X4kSV8IcCySyaRct0aKAcMLu6VHglSSmKYQNOwk/VMU3c6Z0BckdAvVdUhhORkvm
            NZiXBMicXdQm1hACmDP4iZI8jDYRRoRuBKe3e/M0/AbbfZVHJZEOmnu0Zg4EBqYs
            xrcennATA3dlGFruUB3CGcvQD/l7LKXY+fhjqhiALPoggihAT8B7hRViz9rtfTyU
            +CCoGvlH3Trke8SNVjZDKdovyxekzmlb3Js4f0WFoxop2kYThvzNy5+YxMtfwukg
            j7gVrzy+ETTwXsEmWkmPG0m03HC+HrtbcXwoq5iEpp9GUpqHFvA330cmLubmVHby
            QEPcwKyC6Sv77QE9Vzlh+PSrW6Iaqt+a5t6rPpkPxZI+7iKl/GKuYAlAArekV0XY
            3MHIeLbMj1MCYiUKCeLEm6RdIpkqbKbvj9jZn6bBD4+1EXWxt+HiiCbm4CrJ2jnU
            ZgEJAhA6EUSXohkX5N2Q2EzmGWAbyt0pvR2GqLRHjuYs0kDo+O4wfoZtwPM34ugq
            FK2xpzXdU957eA73PbaxXf8ZYbDBUx0E82VaiwHp/WEd3Ru66nenbjwy3qXpf/RQ
            RUbwEVC2Og==
            =2V4h
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
