# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:L7fkNVG6RGx249eCHQ21bv4=,iv:ThXIzwQ17WH9qs6mW2jIOQV27zr0X5MYPbSbr0gIHZQ=,tag:gTIJri2OaZWWnPsOzu8WmA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:O5aCSCCI4vFyqGCTtGB1HhSIMNnULETcL4ZhSrJrkYA=,iv:Sjc99kC5tLyiYYDiP77TVige0o67oiQx9NNFYeYtw0M=,tag:eAPhTC7ALTEvfXiWaDsWvw==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:c6JTUouA89oYyVyiHJLM6+CvdkhHvoPPh1Fsr8Q4TLI=,iv:m5euGOvmSeRwEZzmlqtoA0XMsTJUGhydXJApHnuPOuU=,tag:ZczXolj5dE4J5JFFnynrqQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:X7+2ZJNcmib+A9GRh1jzOJlK2Hu+pCC1hOCHIHi7LaJKqzXx6/L2F1RoTeKGOA==,iv:dfJ2Kj5NpbxWKogIcJuP7n1u0kqWUJk6Z5nCPiSgUro=,tag:OZMucA/khu1h85TD2GXtAQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:tfRgT8k3fD7wzw==,iv:ZFDR+ASxo7y5xP++1vi2h6CG/Pghw30P+0ZEmq4esOY=,tag:kHmdQC2OltdlwvnDx/GGaA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:U/lgiP8+tsFKh8y8ebjaMsDAv1+e/dtsCFn2BYdOKcHwzwIPS8Np7Jd3l0EnMru6FkfSMF8o+PTTD6h8GDs1kg==,iv:rTUWJtFfztr34nk7hzBQHSnOc9Mg8MyZ0OtqGDY3NZc=,tag:xBJFb7ZnZrb7scI2W8wU1g==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:+IZzYd+LsBThMR3qZ4RlX7/M4P5rf90fWsgW/+EXyLEioQcTwVfl6bFIfyaUm84REYCZF5AusBP4ZI3Bvwsi,iv:pIG1f6C6JxvtJ39czkF/ywveyrtixbkDI0kkEVZ5Nwg=,tag:QCT+NodjVGGPVCon4M68aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T14:58:52Z"
    mac: ENC[AES256_GCM,data:id4jfz5qmGyBfmcUx6MkwGXBq7UZZ+UdbeDfodxEpYhOtTrmxMw5ohKXB4Ub4i0aM80lP+0wxuckznFyLwcql8WLtggylMD+x39UYlUNsh5hkKlGK7kj5gmnCR+oZC0lO/F5zJJeenfZQh9nx3ZqqiukdT2g/DwDuKj9A4N2V10=,iv:WqR7Gj3C3t+Tje3Uj4H7DmTtlgT9nz9gIWzx5LokWdQ=,tag:dD55Ea8ZvlNt1yHFoCw+0g==,type:str]
    pgp:
        - created_at: "2022-03-08T14:58:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//YAbDiulQ12PY+gBBnwoAqN6snH5f2SXsAKqhaDkU0c/q
            WJ6JsF8gXInN+fxJcVCRSF20aoYPXKkAFP8l5B93ulsTjKbmfhG0w14PmsKKou1J
            w83DBurW9yqBhMN18xY3caf3pV2EexW1kM2Mm01Up4ULfbDCIo5L0zEKC6u9TBea
            cd6kSht78Q7MCZS0ok8pREKKl/lgX8DE300qYzSk06AgIL6N7N13aRGxg/TqcqMs
            GexYOH/7fBV0eSrOVeOA6nNlxTeES5fDC7NVYTVtTJLa70RRFU7hoVeVEU89hl6K
            x8Osce2WXK199WH3VGNKW3TnEAQLiSCvIlHYEoTOZ9Q2cTijJCnMvcUhuk2EsY4G
            2bMzqpT2dM4rSm7PXDcabO5id0JLEvYpDJong+MvnvduLLeGmlCaeEY7xOR4St61
            v9HjnCVpjnL5Ry7FI40kgrVk5iK0sNuoyMzzxE8rHqXcpJl9NrpbK4QCUYxjGFAX
            KC5HinB+PweDnRT+bPWRKk03OYIbz/1oRRPI8NEzC0+/wqS0LKHfRuDBvvsCRq3P
            dqg8O3Laq03WXgKm2SRqzmNwI25XftsgAXIZwU10zagz5FDfVi3fKv0Gf1nfQI/z
            b5+uSO/xIh5zL7Horr5KY4jUQbTGjuhYKriIo2aIbhgV97FsUMVlljceuCcNt+fU
            ZgEJAhDzJLduc51oHqg+4V/slK1KhuPTZuuc2CPR7gwchgmlJb+Ul4KxEXJTtdJB
            +uvIWMX36aGklvCaNgEECaI7M9yi7Ui7Wo0BbIC11NqDimb+RjNmq9tfk2B+mGYa
            SpbDx2yipQ==
            =wzRS
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
