# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:emzEr8LRpnact8O7K6FFXV1a2w+kTaSVlZhDnqVclgJgBqnu7m+awLIg7Bl/mA==,iv:IiQGyQzPETwP9cRO/A++t2h/mK6Fedv/OoSOyS+peU8=,tag:ofvJuwU4bPeF9SZzelY3/A==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:2YpVoThE3xqBFQ==,iv:a7jsid+5Vh6+5JJPpzUhi0QhVktr/ytjPMcdyTtA1FY=,tag:HJ1s79sUAEuchm/AcvWJFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T12:20:45Z"
    mac: ENC[AES256_GCM,data:VfiDYVqX4LUNK+1KAciE020TAUh/O76UQDjoMiLkY0XxX0w4zzZWUIlik9dKb+2cDefGruITR5DT96vnQXCfX7ecyAjafApULfm+rUdNfGiyOM+W6J6+xkmSPTwK29O0F4qCHQtPpbrjQ+oIju5xxKPJAsv2Nyo4QLFuen0/JZc=,iv:fsRqB7NIst+TuA/05Nc/rA6N4n4kzQT9BGJFeNXqmlY=,tag:GuF6rCBd4CdfQG1FNG0rHA==,type:str]
    pgp:
        - created_at: "2022-03-04T12:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ/9GE4EpPdSeomTLJd8CgPQv8KOEDlZNj4CtXsrmF2C1wId
            +OtWz1/xeadwo3y3pyoBIEJ/0FXCfMNAegExTV0YVsElW6BAh6cmclk5/0s/YNzL
            kOrKagErGIeOnL+RhyIOK+gu1SnfBoBc+7cWixyeZbUCU1xcVU611LRl7BvNFChT
            igFgu/166pK+ymFz5G+aERCqooCQ/jXdhTS2wcUd7ERSXNskrsV0er3ZtcziqnC3
            X1YEje5O5RQ7sQEHgBRqKnjH6GMxxuJWbx8eVAd99PWx4Xm0/BvMKDM3PcfUDUse
            KVO+pP/nq1LkNeDD8EbEkE6Dr8ocRgEMPSo7ReaZa8HaRSvNLDNb6S1sJOYzhB02
            J7Jk6pQmzsZ5qyT57sVKeTA0icrUBlHZytWbZvnZ67w2uvjIObZPlMvivJX6uu3l
            fQ5d+QrwrLjx2rR/MhZg5J3gwCl81F4Q0DN2dDGvL2S2V+8jkymxkXTiX56hyniK
            zscUZUUWhHF9ve5XMCLDl8YLHhccDfvHE2AMYOmQHonedG16Fhxkz6cDRtQmdhs0
            11f8eQne46lfnOZPmI7f5xQpTMHC2/XbXJftCtkFqgzkouY0n6+zN+0TkbxxnVaQ
            6Q31hxPuPgp/vw2vXpZ6rXaXU4K4uYFn++O5nPavhLB4ezUQUyauOJ90RkJg8Z7U
            aAEJAhBG0iMQ4yI0eSju/nmnerAPcxhOp1gTgQercTPgVf1hWZYcDte6b33GLKYF
            Me3qQPwknwVoId510zifPLOSLy07Chp3dYTp8vGXTCV7V1bcv5/SBhMQfek+JmuS
            tUIHHSqAoACx
            =2h2b
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
