# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:PKLMTmIaIDjaivrcSzX+p30=,iv:Gf6mmNIylWqqbz1YYTd54wojFPCUeCWW1PWbzgmgZso=,tag:FSUqMvrekIgUmMPJuQJy0w==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:7W6mEpz9dIbydlXlyiGcFhLroYiHofYloNoJ0m408eE=,iv:PmU9zKI0A78tuRn2h38HNQ3N4tHqvfsaSZ/+Oy/4wFc=,tag:ttgi3UtqYJEwyw2nOeqc2A==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:EsBsyJ7ExR7xQ9WSELkZ6siLQyFFrp76FrFMBRIMClg=,iv:ZfrPrRZzlwFpndFUrMFHV5fAFknvUVGDgX4IhJxBvZQ=,tag:4MKVUQEk/TI8FaDhaq2h2Q==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:vr/MkgYXFi4SRin4vy0IuQjsOfvT3giJmiHGWSR2TQ81NrTM/aa/EszwyzNheg==,iv:JuYdZ2VAcE+Rl0mg1f5nIAaTeaCsnPkonhdosD2PH1k=,tag:HWj7y7JNGkyK+NvM3QXEng==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:QrlWaKDMsJSF4g==,iv:2swNeKvkf2ikv4Nr8OKWwsqaanRuPp8obzVlhyp3D+Y=,tag:kH9Q3NfrgkvSjkDhDRX09w==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:IuuQ9EWJ6/53CCR6lgkHXu49g5s8tOkXAXYkYSF4IfvtZELmII15dVTz/JNEnJZB7pincTA0To8eFJDDjmLZrg==,iv:M1fqpLOZaDPwKboUOvFDeXBmsJ2PGiyhVtRykXemcMA=,tag:A0EVc5NtvTLv7MiI6Yt9mw==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:dGNpp+Lh9mpTqWl6tQkRrShhReaswcPd1jaTuHW8E2sTc9PGHLf6b/+QepkPo3RDSP4TD83JRX6YD6GqrBtd,iv:o1gyySqY/GV65FSIYuN3mJ5u2nHbYBLiPzWEAfPrizc=,tag:Y0NQdoKbz1jyxKOhQVhe+g==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:ryvhSKNWB3/mebJ1Asve1Ai3GJ0KHXMFHQlgSWsI8iS4oCIAzz0/g38mtUsjflkL1lc=,iv:puUuJo3RgQ6dzeE8VQUkyr+4pZ3GskKAzIrqMqJvwtE=,tag:iKIvtuGH9M9kdCqoD3nMAg==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:LmTPNt5v5B7iMl0wWSdDkryxPYVTVwgFp/yEkt+7dbSWCyP2YfVVv2qAKgINeRpu0NM=,iv:+qsn/QokAohF0/ql5AeUWFqS0vFv1RbDBVX/yO8YCEM=,tag:Exv/FvPP+YbdmuJlusXMXw==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:zy13mQdjufcAzJYl,iv:AK3LpT1f5kMl4xHQcPN2HYi5VGuXv2WSKMG/JARbPJE=,tag:Tn00XrIfOhgWNk5g2o+afA==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:piw11yMJp56RbcXja8znl2zSHHEEfrTmsvmlG3hnmZ0=,iv:ImQhUcMt3W7RpBEA9//HxAbdtYSEUzaz0eWsNVPX/pU=,tag:vzVm+zAJoGJnIP1Sc5cOBQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:aSle05UfeBxxl7M=,iv:UuLhdT1tRg7TJ7HIiBgCejLuZY+NXjDwCFRl1O8kjNI=,tag:dnx+6n9wImAouy/h9Id61Q==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:KZM0wk4T/uhk71c2ICb8tGpUEGoPZQ6e/hgCno20FIGV87TqiolAndO3go/Sf0c6htawYyKGl76roOhhRGWkyURVVaMuzPJXv6phEeCZHVZY,iv:AY9q1zRgy7CK1FCbsyLgZMpgcKSjbWyO98BSbVGBKm0=,tag:Cwt/TEZIjj41MQ5DO47Yhw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ai4LJSiydWywyL+NxBh5i/9pzzt80ZlfsdcJik0XfhfhYFO8yD5GVoHkvhtCjfAWgA==,iv:fzrgIZ0LPFb3i0mFRD7UCOb89FoEXBP4dG1uch6GVwc=,tag:ygjj+5J8sRs6BMueSoH2OA==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:V/iz741Mlpezd7Q5df2MnAo8zPnDnFjXEg5yT0C1k4ck+lyLwBWdUrcKQyiGmnYVlyo=,iv:y8HjPB1XOYvam5SJSOLs2V3HUvxKUtPRA12kIWa9NMs=,tag:BjfFyOF9BuqBzN7Hv8xhIg==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:7MGXs/mnFQB6RV5Cam5k6BEhXKXQtmme4wYG4qwk7N+HiSdh+TvQ1aufA8NvdN2eFXI=,iv:FqiHL0JOp0sC+95KWs03vBdSmwnuo2eWTBYZQAuoy10=,tag:S2FujsspuRyvIgnMsAQzxQ==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:t2RxQFygo/4LH7ed49CGgt2xBHMLoA3xTm9mW0nbsfls7KXKrPE6ROnDLWq73oHxc14=,iv:YhrMlNJ1tCrbKND+rnTZ1/i23Gj9bA0v/5yBtuSL+kY=,tag:Lb4Pz24zA/gOZIs2/yxwXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T05:19:04Z"
    mac: ENC[AES256_GCM,data:PKEs/08IqTb5M62mxPQDZ9kXYEl8oaDZ4xaAXb1nD7wbc7YKHbTGvhKXQEs3TzxiOX3bSWl0IHMCmK5CpiQQBedQUMj1SNxLnbdi7cev1gBdoGzKN34HlOVXa+MjNhsGUh8PWIGbFL4W3xAcoQeWtHwwgsNhquOwpwqTtGeITAA=,iv:P3/JKz/5qVwMiJ+YBhB/74XXv1X83+IsYEQFvxS+TCg=,tag:+QqFoR1qD7DoAKntJ7+HzQ==,type:str]
    pgp:
        - created_at: "2022-04-06T05:19:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7ARAAn/sFy+GXIciP2BhsvCXfR7V9ZMzvGMGWxwX7TxxKPG1k
            Ct2IM42fAYq/O+zsyuSIxc65ATqLSkuX806SDayN/ZbT888wP2C/zScEpyQaI8g/
            nCP6yK+gaimNW0H1fCZVBkAiIWe+ubqhuNqF4kLp+bIhk9d98eXvAe0PtL+808C6
            tDjbTcBxWmwkVkVhci4KEBxMsdRX2OywnWz19TlyleYZbFNxI4MyMgJO7AlXnUwb
            Z1XU0APZsIKBM3mjn5UGlT5JnxArIL1wYoiBJDWhz76kWpDQlH2TE9PfGAPTGAOm
            +GXzmyfoHbXcRMm0Zmo3sszzroD349A5R66uBiGN2uO33VztTX2Mcy6HPsf/7Vf8
            ngJRy1aaorCxfYqbetbS4RfTB2shQD4eIy34Ah2bPCW+uWOlL+oNY/eCBXLrlAxo
            sO1Hw8ZgknFEuCXCKJ2ZlnTQvki/lEgKEGGae4OQ3DQu+2ZqlS+PTw8sKA6xPWzy
            p7WukRFQ41vfRhyr5OQhvjd64wG6MWS9wdjjO98Ggt4WwDtzdncOGwPI3LFgCC6H
            sDOw3sqTunnibOpdK7ixr0Vh83LVpw17DaX1vOFLJoQdlQKaoNl4s+UALAVSOXU/
            Szo4poKyrleM4+WoVG1NqE4N4ZuegLmGW7mKsVbdBJvWgATQI/V+dq5vQIgi39vU
            ZgEJAhAh/5FXEuVTRLMw/Hlsa+ynQg0T+/VKhhkfe23AiHrvLGdzNEjGY4Jv8oO9
            5u/Gp0VBjOR17a39P49N75JCgPlvQjGWLWqrr8qW6KSGv804y4B3CtaPE4K015OQ
            oxj8xMK32g==
            =lj4l
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
