# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:yGMnNYWYobnlw0nRjhu92HE=,iv:2AwBfHX2AauDn7O0/SCvVHdzw2pn/8SuNLLSdUXdGvY=,tag:r6r+ByCjzsauV3AbP/ms4Q==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:vVSfzrwCiY/SJ0ppeorC4H6yYCJqmKA+Lw3R15Iqnt4=,iv:5edq2fa2vpw8NxlmpFDZ42X2j0BkbHttHCxtgNGSuCs=,tag:QqITIfWYGLjOvkd3i4K6+Q==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:7r9bOxsM8UQBtULnEpIy57USAwTvylv+79PNP/WtZcA=,iv:yHqWHkjQC2NiFFce+RXHkb2uoMVYSZroe0D7sBC0rZA=,tag:ZcFiR6DORmJ9xr3z0Jl8mQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:F7oMU+zcutJes5z1i12PNJd22/urKJWHaRoJayIGzR+rQAjZGRp6F9+WDSAhhg==,iv:olx5HDAoOqEqqlqh363BDMwRzVYwrsoPTZi3rhV0sfo=,tag:IHnlx5khAVcYYOhrd2eUVA==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:bZ8wQ9m3vhvfzQ==,iv:wnPeKZyE4uXmVs+8V40tyRYoKYMV+WQel7RUyXz534g=,tag:13+rbNw8WiTXoaxpdkuOMA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:MU1AU43w5FgMc+1rj/+aW3NFLoVQ3n4VqCoRJGOKhOSvvOOJ/AUFqB+A6Lnxx/hrE9LpbUoF7xNumRDQ+2pVNQ==,iv:rKCYAKp4mc9sk5zzKoQPkw9Y6tOu1XfZtnrRwBH9NYM=,tag:NBnHfUA5vz9lS2VTK5F6Gw==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:Uy/bsFeVuhgHRnoLEmfHqLDUk67CYEHqTD9wXUkzETdEoOpHANyXRQpd2RwPDBBrxFbMZ3gokQEmt+6NekK/,iv:1mUN4DVkZ+7n18E7VPR7wOQdzAkla8m9tWb5XAAouqc=,tag:By9K7xb7XUNqcz22e92qiQ==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:Vut1N93z58kQ2PN2VL+RcFJam5K7h2CMDOrvIqEgCgsyCvWLoOb4CKyovCZ7TtVI2O8=,iv:OFJHxU/asVN4zLKnqT5zLJd14m9YXvz5+fsfL3k1hnM=,tag:JZpGFcCMDfwPc+Yn6xS8FA==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ddge95bO3Fs9lnLRnTs6lEWvIUeOOZmfOIjKiVYkVAaWVDkb9ESzk8KIfEqyNH1LOZs=,iv:ouk9tohiWq7oJ9WnVXuN3XmXu98zh0FQYFJs0sOR6Qk=,tag:l4aMlNTBGuEDJ4Bf3q+Now==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:epkeSjWcq2DePRgX,iv:jeiSRcxxp6xNna8IA6SxiqQm/ukH2lfjUkXbI6QTz4s=,tag:2fztOafSnjZGSiuQNw3/ew==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:RR81Gj+9gMG9W4CfAZYtJ6ZvXEzTuRCboNy+bNe9ds0=,iv:j2STv3/xVz0NOerlzIFng3jDtnUN4DUR2TTqe9HpGWA=,tag:MST2K/pQkiTQPJLWdGX7Vg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:kglSZLXQJxXFMds=,iv:eqtv+Bk0eRo7gkyHjsXRdLonwAtZcVkPblK4PjQw1y0=,tag:+3Y0QIpBTuVceGPM3rXToA==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:sBFe0gnCknSESvwLbzbodWJJr78UI2zTMv+/26IvkLKS9imwlrY3+3mJLUTfnKSv6Fb7R1P12DMTOVrkxxPQpwHs6cX3tk5vKaseouJqF6XC,iv:kOXx+jLYKhVOQyY0hf/KdOJ2kgZ+MbLx1//Ym3TCn1w=,tag:dIb6g098JYysCUyqIz3kmA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:k9zHB6aEoTo1wNPJYMKxTh/OTGdVeSJr9IR6vOvhqxm/k/H1YLlaMB4bTYqywvZcKw==,iv:WuC1qUznV1+VKty/KkX1Y6P0tpzqSjef1kg/AGUcfIA=,tag:6COKBbt6Tot3/cQFjHmDpQ==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:yCkYLWrq4QQR4QqgEQZ9T9s9q3G5hhAj/Sa0ic+ajxHr/TVv1KLNOL/1mhuqNnAKRhk=,iv:l6wc1Bp7ir1hGxF7RMfSmKnhc2hagjE0qDUXB/NQqQE=,tag:o0PLr+mYasTG6oL4c6KToQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-02T11:00:53Z"
    mac: ENC[AES256_GCM,data:qKMmZ5aGP4EDlKUpSXjQNPq5dyKCjcCvrwNULKymEjcHnpvIUwVSGUHUO0n0AWxOyOWz6ORi7k5ySMNvLtv4FApWsH9A1FkcitHzrS3ilUTPrhho/ejI2xmfWx37fkMWd0ZecpC3uJ1pvn9BgaGvZhVAynZ19elwyeO7QoE5R5A=,iv:q0dUsitk1n4y8/5JmXIiUxUNIuhXkc5N1Jg4zawF5zM=,tag:BBYapH+uh559hThF2Q2CJw==,type:str]
    pgp:
        - created_at: "2022-04-02T11:00:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ//VGDXtvXBPoZl7tgeCxMPTUh2yEny1ZuQWYHvidZzbdUX
            HJcgTlxbCj30AvC7caTff0pDfo2Fmqes8xJ3RCn4hDHIqNsErgTu23n9rlpacXzj
            xpKeBkA9Oao+d7GqGeqIhuQqX+D5wDHxKk4UHZYYvafToGoWrrkf0aCGGzxJB5Ei
            85R9joPtNIgF4aXF/BuK38ybvf+MArbjGAhbuCrZXWTRS78PCKOGyZfilqNTGqdA
            NYj7uTP8ei44erDuitOa5bJDywwbD2MxKdIJpzpJugBCNIt0U8S+EJaCYrL9U8sB
            UqvZZdbd3W+fSOG2D/wJi6nhZop2Nyl1K9x1O/I9zihvzuU8Y8//vj0jJbbtG2CT
            NEkU7K5P8SytWXmSkE35LqATTm0SmKZux7K+UeH3nAd02iKa8mXq/gk/rb3TL+0c
            w/Mgt0aU4McgrFHzqTylFrqMseGFdJVE12evxSYwXOdRLEJQFvI2Wo9s8OvFQIsj
            qyI7MahUOHZyn6thlGIV4r6tc+hgE0YyJsnO8GAA05unQhg77FPLwOJHlN5vACiF
            dzhcQxMG3vJGIDdQ7shjhaqL9K6ugT7oj04gTMyCGHHp92Tr61hKuAbUwk00KDG6
            YEs/5lQKiZULNN2BWt3Ox2hRk4uMYMJ5o3P0qSG//w8t2Q2tY9EDRl8eU3W8w3bU
            aAEJAhD+IheU9+QQMij2HuzuK6mR7G3AdWwhgP18c+yUueQWwiZvDQiamB80R9qN
            aROXMctYSs7eRlYZnyk+VCJobsZhAlfVtKheGLF+d5JnwtkqBoj4xVVb49HchWOT
            qebXUDHWvcGK
            =dYxP
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
