# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:dX7KXVXBiQqESPXag5Z+Tio=,iv:JHjwwigDC2pSqf3IJQx1Sx6m3flNkKc+8tbTkcjNJ3M=,tag:viiT3ZIhJGszBBNQ8ooUyQ==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:itX9iUcWt0gcanFlN38tEKr711LCUYPH1SB+g9/QkXw=,iv:yFdlkf296vLCHqFh8NTmwOwG4mQyA1NrAkUlwWRP58w=,tag:dPn2QgLC62c1lR0DX6VDjQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PmIBx9jjxCxpfOwhQ07Hyg1eKyPw/utFaovrfR9r/eA=,iv:r1ZIKnSBZaCLSp23HB7DAP0nQ9RTt14F4XW5wBwLVFI=,tag:xIHVAd3HXfns+OwBsFaeNQ==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:3cBaj1s+9JS9IeSZP3vnFNx4KNhe0RgMw0ad91gIn/Y=,iv:8k7aDXXbs6iLsA6rhZNtksipEwmH7ZuB5mUxz2bW5ww=,tag:CxCuqTkewoTapLjxncUQJg==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:fKjmvM6uztSVWUxIzgm9XP8DYkwtT2zvqm9ojy6LIt0HFNsADyN5IYAQkgtqKw==,iv:lCd0j6MCacMXl9sfxCMsRZHDawPhX5LkGBJ2pKZ/DQw=,tag:SMEvyxPivx3dposig3VHuQ==,type:str]
    SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID: ENC[AES256_GCM,data:63Qi4cU8XvKrTQ==,iv:ni1sc1tv6GwriA1hhgWGrTpZdmRzHfonjkkPZKOSpsc=,tag:GxX8sMcEq9uRn8Li1FVB2g==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:yrjF024xsfp71zzEajJ3HIAqcBEJgNcxWriqJb4cd+RZtBqoNZ8g8kv/3v7g2nGOD+JbkCKmlNjEy0wWOvaKtA==,iv:pm38fiOr5wASg+gpz6fjdUYKvXs6IEdOQSm/5TCRv54=,tag:eKon2c93/QIoAE3g26GrLQ==,type:str]
    SECRET_VAULTWARDEN_DATABASE_PASSWORD: ENC[AES256_GCM,data:8pd+NEhQbMqWQGz6hJC/N/UL6nveTaS4A9qs4TeLYSdtZdDCOvu1N/rZa+GfCXM634T7d2WRdKvifA/fEkjt,iv:mcGNS5jVnj1xCDu9RXfg3hSd0WTpFqHHaRMxsfC5yjc=,tag:Vm+wlzDx+QVKyCjLJgASvA==,type:str]
    SECRET_NEXTCLOUD_DATABASE_PASSWORD: ENC[AES256_GCM,data:qo9ydWcKwQF2xTihWG59UgjoN0aZM7mDjGIEli9VUGq7gLCKLF21Lx4JPcLgk5h/9U0=,iv:kaEUd/DaXcT8YdRrexN/+83t2er0Cm8AOl6aZ0tBbdQ=,tag:eb53jxdZQs5OyKFNE36GCQ==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:6aSrSeImMqwvJu0AfoX9U6UaYXFIu5VExF6GCH89REKGkju5jQG5iEhL0jbNbFzNz9Q=,iv:QJF82LU2l5xZijFDQ7wm2wHugWLZ7fFVUGa6lwZ6LBM=,tag:oaHdXhiF5/QJHfXLUDn8EA==,type:str]
    SECRET_SYNOLOGY_CSI_USERNAME: ENC[AES256_GCM,data:nM+Zj00JRaO6lyhw,iv:H222WxYlO4fuEjAhgb7+shXjRb/dcdwDP1GDqNUdPaM=,tag:32x3LGcy7WyNqlxErOdVew==,type:str]
    SECRET_SYNOLOGY_CSI_PASSWORD: ENC[AES256_GCM,data:D2hHJR/SMtuKRD9FZnpETW4tDHn3drUR82LK/QFiJio=,iv:slUUHJtkUra7AdMQ0psIzSZs2on97pxROG0ghJS08fI=,tag:qtwUse5dnu8Mo2G+CNOMpA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:yQ+R/KqfzSHl+NE=,iv:Sy0jcsq3syzAWc/Vgn49PtrKTb9RXdRvhndQo19kxfw=,tag:yzQEF29d0Xi+4DFjLjbOKQ==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:6BSvL1D5ob/w2AKtATrzttFVpyp/o2Tot2n+1vRKntV9SgHzzrSADxidnO9gBk876uzqnVLU5XXjQdMM4BzrNC/At2F+WopgJybd9sx+KlOD,iv:iCzChCBjlB+Bn5CePhtTfedY0wGUYzOjF29NJsksOnM=,tag:9zrkVJvwQaskZzAGt00gZA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:E+PT8xmtmG+a/zeiWxpOfeCPx3HT8MFO+TyqEUqYlI8OKtKy2L8IScG3f6T8U5tJWA==,iv:fO5f6N2HIknohgvovc94A8EiIUlh2MDJAqhbXkKxqyk=,tag:9cMDSs9HQXCePXVM9dyKEg==,type:str]
    SECRET_AUTHENTIK_DATABASE_PASSWORD: ENC[AES256_GCM,data:0Xn6TgG2Lqkqqk4Q5yWJS4PDCvCQjAcn4LVDZRQWo0Htb0DF0+4zPd8AgLVSWNUSSDc=,iv:oGGn8ulvNc2omcW7oJVuinEcb98OFZrn2htIHrcJGgg=,tag:qdZ7BwVUS1FsaPpA8hn0sA==,type:str]
    SECRET_KEYCLOAK_DATABASE_PASSWORD: ENC[AES256_GCM,data:un0OgaTQJfXyahoUP6MLjhSMMSJ6bMJ0zrq+AyLIwS26Cx7Lsl2kHZER/VQLEGOhjB0=,iv:+xdNL5q/J2g+g14jO2tqgznup/HFz0qSAONwEuTYZx0=,tag:u9bfYOIfEt/+Ui4vf1eLmQ==,type:str]
    SECRET_KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:Q54kfrKvxCJRYFvaTKmzjLjOhLKWpE/bGr+sPTLiTOYN69Nif26peDk2Xef+zuyhlBg=,iv:aC8FxGXJCvhf3Sv9zR8JR0Z3K06+0M5XAMiFSOPhEZs=,tag:CxFNn7AqwIl/gtyAS5pV6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-06T08:26:40Z"
    mac: ENC[AES256_GCM,data:4Mju2w3wcTwBh+cgVy4qIaA9+x33s7z5eE/s/f+FruE/4PURBK9kthOcKjdSOG7ww8t04wXMNDkVjrgBDqolSS+yC0t1dbylaoPx9uOe30HFL4NbKvsOeOh2r9HiV1tMYcb9ZIQEiqzBcvHJS6tnOV5Wca2FsiDARyDuVgUlbyI=,iv:/gKXVeuMhe52MxZag275KOFHCRkNZZ7rRMY5WJFJMA4=,tag:O9bKGa80STuxEtTdHb9XlA==,type:str]
    pgp:
        - created_at: "2022-04-06T08:26:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7ARAAsAodS55Srx4Q48YHjdgEoJybPKjyEkO/kH+QtH8N2Cqd
            ZWHTvtNk1vxECF0/SSzlzg45Af1Vd/+8hY+nZ/iSVLCwnbZ9EhzS7xsWrw3tljpT
            58OEgVlxAO1rxyVl0OqD92rSt/sNCyG6RIDdB70ZSql+RENIGngpCzh+Ev8F53EN
            LZ9louBEFg9940RsOPkdDX5ErYbzSJ/Xqh12m3N22ib+Nk2b9d76/NhMbQNfxyb9
            Buf3SBvQe1a8ELZw52Dp9OCN5jaGfgBs67g05bpTYKe1U8Zziwc8V6V5KDw3mV1r
            Jo92aDmq1S7gf7R0sEigGOND16RZScdMiVmS9tlgRhVpioYGVOgndxT7/J+E5mIg
            veQxf0j7b75WqPuU/nRGXQ8vdeVYRJgruAFwwLKJGo/I0JjlP0Dsuh0sWiEMeggo
            RB4/1SUs1H46ehPrYvefAyt8i6NRfsF6wDSM7Tl4WAHMOUwlehYNWFppvnyRnwy5
            vCacj/LmMUWt5g1wbM48V2mAbB/P06MBqY/pYSJTY1BJe4qI/0U8vFIycu0qqTy0
            KnM6JZGDDOVRU3X4VATWr0gdoOEDiML4v3Jl5J3u1j5l3mC8WvW50Oie8PNOt9ZX
            9/PEitbpmlM30aMnk6h4xvoxIt6Xu3Kx/FRcz/vM1sSehKTU3oHmomavvYd0L+bU
            aAEJAhB7PKbh4DTA7X2qrkNP3Gf3h/6NRPurgcioEtUJCmH67C2nQooK4Gbt+pUS
            qF0QDh73Pq7+TYWdXm5uJRPTRu6NShWmH76UTXur4wCAPTogZEPoRQCB5ilazC9w
            3aNGRBjY4C14
            =6hxF
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
