---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
      clients:
        - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
          #lokiAddress: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
