---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 33.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: prometheus
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    prometheus:
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1024Mi
          cpu: 500m
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - prometheus.internal.domrocco.de
        paths:
          - /
        pathType: ImplementationSpecific
        tls:
          - secretName: prometheus-tls-secret
            hosts:
              - prometheus.internal.domrocco.de
      prometheusSpec:
        replicas: 1
        retention: 6h
        walCompression: true
        additionalScrapeConfigs:
          - job_name: "node-exporter"
            honor_timestamps: true
            static_configs:
              - targets:
                  - 192.168.180.15:9100
                  - 192.168.178.10:9100
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-sc
            resources:
              requests:
                storage: 10Gi
    prometheusOperator:
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-sc
              resources:
                requests:
                  storage: 1Gi
      config:
        global:
          resolve_timeout: 5m
        receivers:
          - name: blackhole
          - name: alertmanager-bot
            webhook_configs:
              - url: http://alertmanager-bot.monitoring.svc.cluster.local:8080
                send_resolved: true
        route:
          group_by: ["alertname", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 6h
          receiver: 'alertmanager-bot'
          routes:
            - receiver: 'blackhole'
              match:
                alertname: 'Watchdog'
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: false
        hosts:
          - alertmanager.internal.domrocco.de
        paths:
          - /
        pathType: ImplementationSpecific
        tls:
          - secretName: alertmanager-tls-secret
            hosts:
              - alertmanager.internal.domrocco.de
    grafana:
      enabled: true
      defaultDashboardsTimezone: "Europe/Berlin"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - grafana.internal.domrocco.de
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - grafana.internal.domrocco.de
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
