---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600-charts
        namespace: flux-system
  values:
    replicaCount: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - pihole.internal.${SECRET_PUBLIC_DOMAIN}
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.internal.${SECRET_PUBLIC_DOMAIN}
    persistentVolumeClaim:
      enabled: true
    serviceWeb:
      loadBalancerIP: 192.168.180.11
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.180.11
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDhcp:
      loadBalancerIP: 192.168.180.11
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
    admin:
      existingSecret: pihole-admin-password
      passwordKey: "password"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
    podAnnotations:
      prometheus.io/port: '9617'
      prometheus.io/scrape: 'true'
