---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30s
  install:
    createNamespace: true
  releaseName: metallb
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  targetNamespace: metallb-system
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.180.10/32
