---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: haproxy
spec:
  secretName: wildcard-tls-secret
  additionalOutputFormats:
    - type: CombinedPEM
  commonName: '*.internal.${SECRET_PUBLIC_DOMAIN}'
  dnsNames:
    - internal.${SECRET_PUBLIC_DOMAIN}
    - '*.internal.${SECRET_PUBLIC_DOMAIN}'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
