---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: haproxy
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: haproxytech-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    kind: DaemonSet
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.180.12"
    mountedSecrets:
      - volumeName: wildcard-tls-secret
        secretName: wildcard-tls-secret
        mountPath: /usr/local/etc/ssl
    config: |
      global
        log stdout format raw local0
        maxconn 1024
      defaults
        log global
        timeout client 60s
        timeout connect 60s
        timeout server 60s

      frontend frontend_https
        mode http
        bind :80
        bind :443 ssl crt /usr/local/etc/ssl/tls-combined.pem no-sslv3
        http-request redirect scheme https unless { ssl_fc }
        option forwardfor
        acl nas hdr(host) -i nas.internal.${SECRET_PUBLIC_DOMAIN}
        use_backend nas if nas
        acl pictures hdr(host) -i pictures.internal.${SECRET_PUBLIC_DOMAIN}
        use_backend pictures if pictures
        acl drive hdr(host) -i drive.internal.${SECRET_PUBLIC_DOMAIN}
        use_backend drive if drive
        acl plex hdr(host) -i plex.internal.${SECRET_PUBLIC_DOMAIN}
        use_backend plex if plex

      backend nas
        mode http
        server nas.internal.${SECRET_PUBLIC_DOMAIN} 192.168.180.21:443 check ssl verify none
      backend pictures
        mode http
        server pictures.internal.${SECRET_PUBLIC_DOMAIN} 192.168.180.21:443 check ssl verify none
      backend drive
        mode http
        server drive.internal.${SECRET_PUBLIC_DOMAIN} 192.168.180.21:443 check ssl verify none
      backend plex
        mode http
        server plex.internal.${SECRET_PUBLIC_DOMAIN} 192.168.180.21:32400 check ssl verify none
