---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      DOMAIN: https://vaultwarden.${SECRET_PUBLIC_DOMAIN}
      DATABASE_URL: "postgresql://vaultwarden:${SECRET_VAULTWARDEN_DATABASE_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden"
      ADMIN_TOKEN: "${SECRET_VAULTWARDEN_ADMIN_TOKEN}"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      SMTP_HOST: "mail.${SECRET_PUBLIC_DOMAIN}"
      SMTP_FROM: "vaultwarden@${SECRET_PUBLIC_DOMAIN}"
      SMTP_PORT: 587
      SMTP_SSL: true
      SMTP_USERNAME: ${SECRET_SMTP_USERNAME}
      SMTP_PASSWORD: ${SECRET_SMTP_PASSWORD}
      TZ: "Europe/Berlin"
    persistence:
      config:
        enabled: true
        storageClass: nfs-sc
        size: 5Gi
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "homelab-tunnel.${SECRET_PUBLIC_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        ingressClassName: nginx
        hosts:
          - host: vaultwarden.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - secretName: vaultwarden-tls
            hosts:
              - vaultwarden.${SECRET_PUBLIC_DOMAIN}
    postgresql:
      enabled: true
      postgresqlUsername: vaultwarden
      postgresqlPassword: "${SECRET_VAULTWARDEN_DATABASE_PASSWORD}"
      postgresqlDatabase: vaultwarden
      persistence:
        enabled: true
        storageClass: nfs-sc
        size: 5Gi
        accessModes:
          - ReadWriteOnce
