---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.6.6
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    hostname: rancher.internal.${SECRET_PUBLIC_DOMAIN}
    ingress:
      tls:
        source: secret
        secretName: rancher-tls-secret
