---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.16.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    configuration:
      annotateNodes: true
      timeZone: "Europe/Berlin"
      prometheusUrl: http://prometheus-prometheus.monitoring.svc.cluster.local:9090
      alertFilterRegexp: ^(Watchdog|HostOutOfMemory|RebootRequired|RebootScheduled)$
      period: "15m"
    metrics:
      create: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
