---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager-bot
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: alertmanager-bot
      version: 6.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/Berlin"
      STORE: bolt
      BOLT_PATH: /data/bot.db
      TELEGRAM_ADMIN: ${SECRET_ALERTMANAGER_BOT_TELEGRAM_ADMIN_ID}
      TELEGRAM_TOKEN: ${SECRET_ALERTMANAGER_BOT_TELEGRAM_API_TOKEN}
      ALERTMANAGER_URL: "https://alertmanager.internal.${SECRET_PUBLIC_DOMAIN}"
    service:
      main:
        enabled: true
        ports:
          http:
            port: 8080
            targetPort: 8080
