---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: monitoring
  name: &app healthchecks-heartbeat
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
            - name: *app
              image: ghcr.io/k8s-at-home/kubectl:v1.25.1
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - &scriptPath "/app/healthchecks-heartbeat.sh"
              volumeMounts:
                - name: *app
                  mountPath: *scriptPath
                  subPath: &scriptName healthchecks-heartbeat.sh
                  readOnly: true
          volumes:
            - name: *app
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: *app
                      items:
                        - key: *scriptName
                          path: *scriptName
