# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-heartbeat
    namespace: monitoring
stringData:
    HEALTHCHECKS_PING_URL: ENC[AES256_GCM,data:IlgHkVVmjXQ3r86MBt+Tyt8sri+IKAg82ZVmoyBKFM7oNkBRXNj0oTdRlNsbRA3IHZDaSgCdQrU=,iv:8kLuHiFY+vWkA9XDUh1XAmxbEAqUPU4SgWWdBoLbtng=,tag:+/xI0BXuSm6nfFvDD47d3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-07T12:15:25Z"
    mac: ENC[AES256_GCM,data:OtfwH6H/43pbl1k1cbEmTpxO1d25PXao5+C5irAQcvB4Z/o29WvmfJwYxjamone/oJ5Gtzmgi8nqZkF0OAQxawIzgHZtHGGJCrCpqBdFXF2HVINnFHioLpwkal4kwuOdTrQ4VN9I900du2T5RMQcBOTfLL2eK/iJ/Mk3xbKQO4A=,iv:ZFhjziP+BpJ9ZMjgqGBT9Ud/D/OsPsa0mwIA26kSL74=,tag:dW3TjW0CUGDCv9TXCkdirQ==,type:str]
    pgp:
        - created_at: "2022-08-07T12:15:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7ARAAhaxxoRhlqsFNVKO1FaNzvfOl5Ni0NumVeVuEr+4rDg+d
            0J4D/jpQZ3aTahG+lrxvK0Joym5xz8QMVU2eh3Uk+enseGw3HF+iExKGavvp+Rzf
            907+ApSRClzQciXFck/DSW5y3Z98OjGG78KvScUs7FirkQchwAUn8IkFNIMjpEEx
            k91ct1MbGJ8XxgLoF3m9iAdnQQmQ/Gr9NJctFehaAeR1jLaNuszfotcWrGPhRLsW
            49LNOoOTKEp0tvI96MLRL84H6Z1e7t/XQAm3jMM43iHRV2zL3PvF9wIjS2S0tIiz
            TYAtS0p2+oVZQ2TY0yKISIL1UVhMmVTytrZ9NQ7xugreD6gk53ozePP8a9Abk399
            Wqirg97wloxqkCdOghGcZFY43Nv8aDZk5nDE6lh5dwjj8FIDLM0F9CRER7/kCuee
            OfM5nqS6uuMJxUVQk334/0Zg5qRIrA0q4cfIGLmjG5MZmTYTtSsKNF21K2lnpoDJ
            NuJ5GJb3cOAqV5Vvw4fxjRp9Yxq4VgouERJGGg4xKBc6WgplDQs2wl6XbO+gqDcd
            QtXjIqp25wNI290Yx3Qaf+qy6lSToNgSFLwUnp/5coo86xUHjiQ0dmAT/1FU3rdw
            XXhDavakPdrrI3mnpbHWNqwKyzMha3NqIMw3WA0I/89ipUMRqIXEd8A0apsJHbrU
            aAEJAhDzl7av7a+pjEaqaJVT2MegurmHwkDYzHCEpUnzu5oG8qXn6tySBis0sjSZ
            +ZAc66fKkDmpHmIUMq4O0PfeTwjs7ywXmhHmKJxeQQCSr/17EYE2aWBbkpZ8xjOn
            /wd5dHEiI31e
            =GBBO
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
