---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: synology-csi
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: dcardellino-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    connections:
      - host: 192.168.180.21
        port: 5000
        https: false
        username: ${SECRET_SYNOLOGY_CSI_USERNAME}
        password: ${SECRET_SYNOLOGY_CSI_PASSWORD}
    storageClasses:
      delete:
        isDefault: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          dsm: 192.168.180.21
          fsType: ext4
          location: /volume1
          type: thin
      reclaim:
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          dsm: 192.168.180.21
          fsType: ext4
          location: /volume1
          type: thin
