apiVersion: v1
kind: Secret
metadata:
    name: ubuntu
    namespace: system-upgrade
type: Opaque
stringData:
    upgrade.sh: ENC[AES256_GCM,data:vw7Wu1KlwoRlnRRxlbEvUxmsO+HWQ6sggIQ2RIqLLtgydO5yi4b66aBOSNQ14VdGazM/dcHC87gvY5Svc+6WuYGP22bbgVWgWNX17WTLDpESx8xYxXegZmZxqn3pj1U/8FcNgJOdL+fWZOOduzc0/3NPEXagc18eakUX6Iec478ub5vwgOKamvbMdIJrndhr9hazyZLk3ZLbA3PDLKnqAGaMTJzkp/oSUWL+ppC4pZlmV4zw+/rogjs1J+k=,iv:HFA0rg20CgvHnGmN7eqCsh0syHw+O50IJ3cPZKkDPog=,tag:CS+/Yq0Xv2rBu9uHCgTNNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-19T15:59:16Z"
    mac: ENC[AES256_GCM,data:YjQSd/Cf5IpKmI0uFVc/x5Ap951Nr3r4Qkk8DYKjNz3nP2KAVulY4K9+PRkyyGTGISwbaiofKtzW9LszC0b399EI8JfW4guvK+wX4yBa5e8BgYos4bzhAKDNME9sV1oWuE2Ip48r5lVS/MKOJVmmSOxWf7iz+7dC1ojGbX2Z/0c=,iv:WzXpl1pYnMDxcpEg5ODIlO1s13y7J/K+Dkrk8pfOR44=,tag:SuCFaYSFaWyJr6NdVKyHRA==,type:str]
    pgp:
        - created_at: "2022-03-19T15:59:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyEF7c5MSrc7AQ/6AuvAgpzokTOhbmSY5KeaG1cK398Th3NTYkiHmpV7MqB4
            dPu4hoXPO45Y3i2NKFolCDKuP0AGCsZcFI5PLV+1yqRKSlG96CTb2+izDM8qZlea
            VRPn/XLY7uer/0EUHLkSqmitrFXXe6zbl4achTTTKE9cSevW5v06NqJeEd/z/1wm
            q+7LQjTwwokJLTpJvr0dT9P637QEZ4rmkSfmyoWhlhaPXjtQ08ZJnTg3ObvYIxdh
            96jpo3azqBhWBwo8RPIPA8doxSnA/2XRgewSBULhxuzBQCpa7PCEoOOhZiX1PBT0
            5ZzzsLwCmYAqkbsVW/w8fjDV9zhShTZIt3/l3XTIaKtQ47av9bIhim+xMkW7mCOp
            puq7fAwi89AQ0MYELn17i6K35BXyIm9kAhkQ3V4hEQR7X65xM5arLNB+eL1xbnEy
            YHRFsX9EujvxdEfPbmmoiggka5S1CvfswsLgGqihmG9Xp2177rpy2OloOzIEbyhM
            EWuiX8UZfIW/3/t++hzsYP3xqGWnljcQp5qSqa3H3Xsrc8zaY8zmtpM5lggPv0Jc
            4yrDldjXkKXpiTyGGwXhFZRZc1zusK669g7Of41pJCzb0LpvrhcakFDvrcsxWxHP
            dAHMPvWbMQ9U3+M54n9v4ehiSGN0umTl4X/cBBaAfob9uV0cAXuHAE3Sv8kW/aPU
            aAEJAhBPFGgTn6ZSq4rD/PBLkNS0ERmzmfZ9Z0CTodFMEYK4/JyTu0KTMcArAs4f
            Jg9YacTcUePPWeoGgNtiGTRWKQdvgGFBu78x9udH5eRQsk5VP8yS3Sr6O48ZdLHE
            4sXTSbw99TbN
            =HD0N
            -----END PGP MESSAGE-----
          fp: 72077FE68DF3F319722FD071B6876F08C070F7E1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
