---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: ubuntu
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - { key: plan.upgrade.cattle.io/ubuntu, operator: Exists }
  serviceAccountName: system-upgrade
  secrets:
    - name: ubuntu
      path: /host/run/system-upgrade/secrets/ubuntu
  drain:
    force: true
  version: focal
  upgrade:
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/ubuntu/upgrade.sh"]
